### ISSUE TITLE
Linter does not work if there are brackets characters in file path

### ISSUE THREAD

**Issue by rcdmk** [SublimeLinter/SublimeLinter-eslint#113]
I have some files with `(` and `)` characters in their path: "some-route-module-(id_module)-get/file.js"

When I run the plugin, I get an error in the console telling me that part of the path was unespected.

I've edited the plugin file "linter.py" and changed the line 91 from:

```
cmd[cmd.index('__RELATIVE_TO_FOLDER__')] = relfilename
```

to:

```
cmd[cmd.index('__RELATIVE_TO_FOLDER__')] = '"' + relfilename.replace('/(\(|\))/', '\\$1') + '"'
```

Added quotation marks around the path and escaped the brackets with slashes and it fixed the problem.

**Comment by roadhump** [comment]
What OS do you use? It seems working fine without escape on MacOS for me.

**Comment by rcdmk** [comment]
I'm on Windows 7 64bit.

**Comment by roadhump** [comment]
Sorry for delay, can't find win machine.
It looks like ST bug https://github.com/SublimeLinter/SublimeLinter3/issues/355 . I can try to screen names until they fix it.

**Comment by roadhump** [comment]
Should be fixed here b947e15bac0109fba4e28f28bfd243b10e092907

**Comment by darkred** [comment]
This commit fixes it, but unfortunately not all cases.

Please try this (i'm using `eslint` 2.2.0 with `Sublimelinter-eslint` 1.9.4 in  `ST3` build 3107 in win 10 x64):
create in `C:\Users\User\Desktop`
a file named `New Text Document (3).js`
having as content `banana = ;`
it won't get linted.
Rename it to e.g. `3.js` and it will be linted.

Also, if now you move the `3.js` file inside a folder such as 
`C:\Users\User\Desktop\New folder (2)`
it won't be linted either.
Renaming the parent folder from `New folder (2)` to e.g. `2` fixes the issue.

**Comment by darkred** [comment]
The above commit fixes the issue, but unfortunately not in all cases.

Please try this 
_(using `eslint` 2.2.0 with ``Sublimelinter` 3.6.1, `Sublimelinter-eslint` 1.9.4 
with `ST3` build 3107 in win 10 x64)_:

create in `C:\Users\User\Desktop` 
a file named `New Text Document (3).js` 
having as content `banana = ;`
and open it in ST3: It won't get linted.
Rename it to e.g. `3.js` and now it will be linted.

Also, if now you move the `3.js` file inside a folder such as 
`C:\Users\User\Desktop\New folder (2)`
it won't be linted either.
Renaming the parent folder from `New folder (2)` to e.g. `2` fixes the issue.

**Comment by braver** [comment]
We're tracking this in https://github.com/SublimeLinter/SublimeLinter/issues/355.
