### ISSUE TITLE
locally installed eslint is not found if package.json is more than 1 level deep

### ISSUE THREAD

**Issue by tnrich** [SublimeLinter/SublimeLinter-eslint#116]
Hey there,

So here's a path to a file that isn't being linted correctly: 
`openVectorEditor/app/ve-range-utils/exampleFile1.js`

Here's the error:

```
SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
SublimeLinter: ERROR: eslint cannot locate 'eslint' 
```

However, files with a path like: 
`openVectorEditor/exampleFile2.js`

Do get linted correctly (eslint has no trouble finding the locally installed eslint: `openVectorEditor/node_modules/eslint` )

I believe this issue is caused by having package.json's defined at multiple levels within the project:
`openVectorEditor/package.json` (with eslint dependency)
and here:
`openVectorEditor/app/ve-range-utils/package.json` (no eslint dependency)

When I remove the package.json at `openVectorEditor/app/ve-range-utils/package.json`, eslint starts working again. This seems like it is clearly a bug to me. Is this a known issue? Is this an issue with any sublime-linter package?

Any help would greatly appreciated. Thanks!

**Comment by roadhump** [comment]
I suppose it is related to #108

**Comment by tnrich** [comment]
Yup, and related to: https://github.com/SublimeLinter/SublimeLinter3/issues/229

**Comment by benmosher** [comment]
This should be fixed in the latest version of SublimeLinter. :smile:
