### ISSUE TITLE
Ignores .eslintignore

### ISSUE THREAD

**Issue by willmruzek** [SublimeLinter/SublimeLinter-eslint#13]
Currently the SublimeLinter plugin doesn't respect an `.eslintignore` file. This becomes distracting when editing a file that I would not like to lint (because of very different rules).

**Comment by darrentorpey** [comment]
I believe this is the correct way to do this:

```
```

**Comment by danvoyce** [comment]
Neither of these work for me :/

**Comment by ethanchen** [comment]
This works for me
```
{
    "linters": {
        "eslint": {
          "args": [
              "--ignore-path", "${directory}/.eslintignore"
            ]
        }
    }
}

**Comment by ethanchen** [comment]
if you use save sublime-project to other dir,  it can be relative to [this setting for sublime-project](http://www.sublimelinter.com/en/latest/settings.html#project-settings) 

```
{
	"folders":
	[
		{
			"path": "/Users/Ethan/Sites/envs"
		}
	],
	"SublimeLinter":
	{
	    "linters": {
	        "eslint": {
	          "args": [
	              "--ignore-path", "/Users/Ethan/Sites/envs/.eslintignore"
	            ]
	        }
	    }
	}
}
