### ISSUE TITLE
Linter is not using globals set in .eslintrc.json

### ISSUE THREAD

**Issue by smlombardi** [SublimeLinter/SublimeLinter-eslint#138]
My project has an .eslintrc.json file:

``` json
{
    "env": {
      "browser": 1
    },
    "extends": "standard",
    "plugins": [
        "standard","angular"
    ],
    "globals": {
      "angular": 1,
      "$": 1,
      "angularDragula": 1
    }
}
```

However, the linter still flags these global items as undefined.  Atom's linter correctly uses this file.  I have even tried renaming it to the older .eslintrc, but this linter is still not picking up the globals.

**Comment by roadhump** [comment]
Hm, and what about if you run `eslint` from command line?

**Comment by smlombardi** [comment]
Same thing happens from command line, but the Atom ESlint picks up the settings in .eslintrc.json

**Comment by smlombardi** [comment]
Note: if I use this: `eslint -c ~/.eslintrc.json feedback-alerts.controller.js` the command line works fine.

However, the sublime linter still flags angular as not being defined and it flags semicolons although the config says to use the semistandard plugin (which allows them).  So it does not correctly read the config.  

Is there a setting to explicitly point it to the config file?  I would've thought it would look in the project folder and then the user home folder.

**Comment by AaronHarris** [comment]
I have the same (very similar) eslintrc above. I put renamed by .eslintrc file to .eslintrc.js and it causes this plugin to break: doing it in console I get 

```
Cannot read config file: /home/aaron/projects/sample-todos/.eslintrc.js
Error: Unexpected token :
SyntaxError: Cannot read config file:  /home/aaron/projects/sample-todos/.eslintrc.js
Error: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports ( /home/aaron/projects/sample-todos/node_modules/require-uncached/index.js:14:12)
    at loadJSConfigFile ( /home/aaron/projects/sample-todos/node_modules/eslint/lib/config/config-file.js:163:16)
    at loadConfigFile ( /home/aaron/projects/sample-todos/node_modules/eslint/lib/config/config-file.js:202:22)
```

However the syntax of the .eslintrc.js file validates on jsonlint and it works fine if I keep the file .eslintrc

**Comment by roadhump** [comment]
@smlombardi You can set CLI config in plugin settings https://github.com/roadhump/SublimeLinter-eslint#i-want-to-use-custom-rules-global-eslintignore-file-etc

**Comment by roadhump** [comment]
@AaronHarris `.eslintrc.js` should be a JS file, like `module.exports = {/*config*/}`, I suppose. You should rename your config file to `.eslintrc.json`

**Comment by kaste** [comment]
Closing due to age
