### ISSUE TITLE
Cannot set --rulesdir to project root for ESLint <2.0.0 for custom rules

### ISSUE THREAD

**Issue by stephenburgess8** [SublimeLinter/SublimeLinter-eslint#140]
Hi

Using  "eslint": "1.10.3"

A teammate has defined a custom rule for ESlint. When I use the SublimeLinter.sublime-settings user settings to set the rulesdir for this, it is unable to parse my project root path and always appends the path string to whatever location a current file is in (lint on save). So, if I'm in `project-root/foo/settings.jsx` and hit save, it looks for the rules dir in `project-root/foo/~/config/eslint-rules`. Similarly this also works if instead of a tilde I use a slash, or if I use the `${project}` syntax. No matter what it appends that string value to the relative directory of the current working file. I've tried all the different ways I can think of to form this differently but it does not parse the directory string, only appending it.
#### `SublimeLinter` console output

```
SublimeLinter: eslint: settings.jsx ['/Users/sburgess/dev/github/gray-wolf/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--rulesdir', '${project}/config/eslint-rules'] 
SublimeLinter: eslint output:
ENOENT: no such file or directory, scandir '/Users/sburgess/dev/github/gray-wolf/app/portals/live-editor/components/${project}/config/eslint-rules'
Error: ENOENT: no such file or directory, scandir '/Users/sburgess/dev/github/gray-wolf/app/portals/live-editor/components/${project}/config/eslint-rules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at module.exports (/Users/sburgess/dev/github/gray-wolf/node_modules/eslint/lib/load-rules.js:32:8)
    at Object.load (/Users/sburgess/dev/github/gray-wolf/node_modules/eslint/lib/rules.js:40:20)
    at /Users/sburgess/dev/github/gray-wolf/node_modules/eslint/lib/cli-engine.js:416:19
    at Array.forEach (native)
    at new CLIEngine (/Users/sburgess/dev/github/gray-wolf/node_modules/eslint/lib/cli-engine.js:414:32)
    at Object.cli.execute (/Users/sburgess/dev/github/gray-wolf/node_modules/eslint/lib/cli.js:160:22)
    at /Users/sburgess/dev/github/gray-wolf/node_modules/eslint/bin/eslint.js:41:28
    at ConcatStream.<anonymous> (/Users/sburgess/dev/github/gray-wolf/node_modules/concat-stream/index.js:36:43) 
```
#### `eslint` output from command line

Running this in the command line does not result in an error, but running without the rulesdir flag does.

```
node_modules/.bin/eslint app/portals/live-editor/components/settings.jsx --rulesdir config/eslint-rules/ --cache
```
#### Additional info if needed (ST version, OS, configuration)

ST3 build 3114
MACOSX 10.11.4 

I have set the args in sublime-settings to have the rulesdir flag as well as having `"--stdin-filename", "**RELATIVE_TO_FOLDER**". If there's any other way to set that flag I haven't found it.

Thank you.

**Comment by roadhump** [comment]
It looks like `rulesdir` will work only with absolute paths now. There is no reliable way to get current working dir in ST now https://github.com/SublimeTextIssues/Core/issues/911 and to pass it to `eslint`.

**Comment by kaste** [comment]
Fixed in SL4
