### ISSUE TITLE
.eslintignore is not loaded in subdirs

### ISSUE THREAD

**Issue by ratherblue** [SublimeLinter/SublimeLinter-eslint#144]
If  you clone this project https://github.com/ratherblue/sublimelinter-bug and open it in SublimeText, you'll see that `./test.js` is successfully ignored, but `./js/test.js` isn't (despite both files being ignored in `.eslintignore`)
![ignore-bug](https://cloud.githubusercontent.com/assets/993432/16325269/72883c68-3971-11e6-8cb7-da4d82ea1333.png)

I dug into the eslint code some and basically `.eslintignore` isn't getting loaded for files because `process.cwd` is the path of the file you're on. (e.g. this line: https://github.com/eslint/eslint/blob/master/lib/ignored-paths.js#L50)

In the linked demo, when I am editing `./test.js`, the `cwd` is `C:\dev\sublimelinter-bug`, which is good.
But when I am editing `./js/test.js` the `cwd` is `C:\dev\sublimelinter-bug\js` which means eslint is looking for a `.eslintignore` file in the `js` directory, which there is none.

I don't know if this is an ESLint bug or a SublimeLinter-eslint bug. Can SublimeLinter-eslint call the eslint process from the project folder root? Then it would successfully load the ignore file.

Note: I am using Windows 7, with Node v4.2.4, ESLint 2.13.1, and Build 3114 of SublimeText

**Comment by ratherblue** [comment]
This is fixed in my pull request #145, but it stops working if you upgrade to ESLint 2.5.3 because of eslint/eslint#5694

**Comment by kaste** [comment]
Should be fixed in SL4
