### ISSUE TITLE
alternative to global/local install - install specifically for sublime only?

### ISSUE THREAD

**Issue by Pomax** [SublimeLinter/SublimeLinter-eslint#147]
Needing to install eslint globally interferes _wildly_ with projects that require a different version of eslint in their package.json, whereas not installing globally leads to projects not being lintable if they either don't have a package.json, or do but do not allow modification of the package.json purely for Sublime purposes.

Is it possible to update the code so that ESlint gets installed in a user directory specific to this plugin, so that it can load the code it needs, without polluting either the global scope or project-local filesystem?

Looking at http://www.sublimetext.com/docs/plugin-basics, it would appear that location already exists (on all platforms), so it feels like it should be (I'm tempted to say "trivially", but I've not written a sublime plugin) possible to have this plugin install eslint for itself in its own plugin dir and then load the code it needs from there, without interfering with the rest of the system.

**Comment by benmosher** [comment]
How does it interfere with other projects? Their version (if spec'd in their `package.json`) should be `npm install`ed and used, presumably. If that isn't working, it's arguably a bug in the package's build script(s).

Locally installed `eslint` should trump global `eslint` (as long as you `npm i` the local package)

**Comment by Pomax** [comment]
practical example: not every codebase is a node project with a package.json, and I don't want my entire computer to be forced into a specific eslint just because I need a good linter plugin in sublime. That case falls between the two extremes currently available, so having eslinst install to a place where this plugin, specifically, knows to look for, and a choice whether to respect a package.json or use the plugin's version, would be fantastic.

**Comment by roadhump** [comment]
@Pomax Probably you should try to tinker `$PATH` somehow to make it point to your separate `eslint` installation http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#debugging-path-problems. For example, try to use `nvm` https://github.com/creationix/nvm and `path` settings of SublimeLinter. It does not allow to set separate `eslint` per project, but you can change it depending which project you work with, I suppose.

**Comment by benmosher** [comment]
I still don't understand what you mean by 

> my entire computer to be forced into a specific eslint

In what case would you want to some ESLint version globally that is different from the version you would choose to use in Sublime? 

i.e., for non-Node JS projects, wouldn't you want a global ESLint? (and why wouldn't it be the same as Sublime's version)

I guess I still don't understand this statement:

> Needing to install eslint globally interferes _wildly_ with projects that require a different version of eslint in their package.json

The whole npm/Node package loading system is built so that that statement is untrue.

**Comment by Pomax** [comment]
short answer: shitty projects that require a global eslint that is an older version, and no direct input on their package.json or because it's not your project.

**Comment by alanmoo** [comment]
This can be a pain using when nvm as well- if I'm depending on a global version of eslint, I have to install it every time I use a new version of node than I'd previously used.

**Comment by benmosher** [comment]
Ah, points taken. Makes sense.

**Comment by mrmowgli** [comment]
Indeed, or being able to specify a specific path.  I'm actually using the n version manager and  I would prefer to have a separate folder for specifying the version of eslint I am running rather than relying on it picking up my globals.

**Comment by braver** [comment]
There are more cases where someone may want to specify the executable precisely. We're tracking this here: https://github.com/SublimeLinter/SublimeLinter/issues/781
