### ISSUE TITLE
'unicode-bom' rule errors are not shown

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter-eslint#149]
_Using ST3 3120 x64 in win10x64 
with ESLint 3.2.0,  SublimeLinter 3.7.4, Sublimelinter-contrib-eslint 1.10.0_

The issue is that `unicode-bom` rule errors are not shown 
 _(maybe it's an issue of SublimeText and not of this package)_,
To reproduce:
- unzip + open the attached file [test.zip](https://github.com/roadhump/SublimeLinter-eslint/files/392073/test.zip) in ST3  (notice that it uses "UTF-8 with BOM" encoding)  
  which contains just this:

```
/* eslint unicode-bom: ["error", "never"]  */
```
- the `unicode-bom` error is not shown  
  (there's no relevant error in console).

<br/>
And, here is what ESLint CLI reports:

```
  1:1  error  Unexpected Unicode BOM (Byte Order Mark)  unicode-bom

✖ 1 problem (1 error, 0 warnings)
```

**Comment by darkred** [comment]
CC'ing @FichteFoll: maybe it's an issue of SublimeText and not of this package?

**Comment by FichteFoll** [comment]
If the linter fetches text from the view (which they usually do), it won't have a BOM. The error would only be shown if the linter is configured to send in the filepath, which would only happen on-save.

However, linters can access the view object they are operating on and manually add a check for the view's encoding setting.
