### ISSUE TITLE
Suggestion: TypeScript support (since eslint/typescript-eslint-parser)

### ISSUE THREAD

**Issue by oriSomething** [SublimeLinter/SublimeLinter-eslint#153]
since there is a new experimental TypeScript parser, it could be helpful if it will be supported at this project as well.
i've tried to find a way to configure the file types in the [docs of sublime lineter](http://www.sublimelinter.com/en/latest/index.html), but i didn't find :/

thanks!

**Comment by roadhump** [comment]
@oriSomething I can add `.ts` syntax to plugin, but it will cause all TypeScript files to be linted by eslint even there is no `eslint/typescript-eslint-parser` plugin. Unfortunately SublimeLinter does not allow to set list of syntaxes per project, which would be a solution. I can only suggest for you to clone this repo to ST plugins folder and add TypeScript to `syntax = (...)` string

**Comment by w0rp** [comment]
I recommend making this configurable, so you can change a setting for the plugin to enable checking TypeScript files with ESLint. The way I handled this in my plugin for Vim is to enable ESLint for TypeScript files by default, and the linters can be enabled or disabled for JavaScript and TypeScript files separately. Whenever parsing errors from ESLint are encountered, I include a hint to install typescript-eslint-parser in the error message.

**Comment by kaste** [comment]
Please try https://github.com/SublimeLinter/SublimeLinter/pull/994
