### ISSUE TITLE
Value "[object Object]" has more items than allowed.

### ISSUE THREAD

**Issue by asaadmahmood** [SublimeLinter/SublimeLinter-eslint#154]
Do let me know if you need the complete console output. The issue is simple, eslint is working normally via terminal but not in sublime text.
#### `SublimeLinter` console output

```
Error: /Users/asaadmahmood/Git/projects/go/src/github.com/mattermost/platform/webapp/.eslintrc.json:
    Configuration for rule "no-self-assign" is invalid:
    Value "[object Object]" has more items than allowed.
```

Insert console output here.
#### `eslint` output from command line

Help: Use the same `eslint` instance which plugin uses (check console output). Run in terminal (Just some portion of it): 

```
  834:27  warning  No magic number: 1000                                     no-magic-numbers
  834:34  warning  No magic number: 60                                       no-magic-numbers
  834:39  warning  No magic number: 60                                       no-magic-numbers
  834:44  warning  No magic number: 24                                       no-magic-numbers
  834:49  warning  No magic number: 15                                       no-magic-numbers
  843:36  warning  No magic number: 5000                                     no-magic-numbers
```

Insert command line output here.
#### Additional info if needed (ST version, OS, configuration)

Sublime build 3114, and mac 10.11.6 (15G31).

**Comment by kaste** [comment]
Closing due to age. The plugin does not parse the eslint config file, so it's unlikely an issue with SublimeLinter and more likely that it's running a different version of eslint or from a different working dir. 

Closing now doesn't mean we can't reopen later, but please be sure to upgrade to SL4 beta bc we don't fix SL3 anymore.
