### ISSUE TITLE
add workaround for using nvm to readme

### ISSUE THREAD

**Issue by jeffijoe** [SublimeLinter/SublimeLinter-eslint#159]
I don't think it matters much what version of Node is used, so running this should let you keep using nvm with oh-my-zsh:

```
ln -s $(which node) /usr/local/bin/node
```

Maybe we want to add this to the readme?

**Comment by mattlub** [comment]
note it should be `which node` not `where node`

**Comment by jeffijoe** [comment]
@mattlub `where` seems to work as well but also lists other versions, so yes `which` is better :+1:

**Comment by kaste** [comment]
Hi, this plugin was unmaintained last year. It is now in the SublimeLinter org. But, honestly, I don't know what you're talking about here?

Is this an issue or can we close?

**Comment by jeffijoe** [comment]
Basically just a suggestion to add a known workaround for nvm users. The linter fails if it cant find the node executable, which seems to be the case when using nvm 😀

**Comment by kaste** [comment]
Can't you just invoke NVM with eslint

**Comment by jeffijoe** [comment]
The plugin needs to invoke eslint. The problem is that when using nvm, it seems to be unable to find node

**Comment by kaste** [comment]
But generally you could run nvm run ... eslint. That is one command, not spawning a subshell?

**Comment by jeffijoe** [comment]
I don't know `nvm run` — if that does work, perhaps have the plugin check for the existence of `nvm` and run that instead of `node`?

**Comment by kaste** [comment]
Okay, closing. 

For python there is something similar called `py`, you can execute `py --3.6 -m flake8` and it will just run `flake8` using python v3.6. So, all that matters here, that you have program `py` and you can write a simple command which will do the right thing. (For nvm it's either nvm run or nvm exec.)

For SL4, you could now specify `executable: ['py', '--3.6', '-m', 'flake8']` in your project settings, and it should just work.
