### ISSUE TITLE
ESLint Crashed for Line number out of range

### ISSUE THREAD

**Issue by Jamie-Yang** [SublimeLinter/SublimeLinter-eslint#162]
In HTML file, the <script> tag has 4 space indent

```html
    <script type="text/javascript">
      var uAgent = window.navigator.userAgent
    </script>
```
this makes eslint crashed
but if there is no indention before </script> , then no crash,  SublimeLinter also works correctly.
what can I do? please help

#### `SublimeLinter` console output

```
SublimeLinter: eslint: index.html ['/Users/jamie/.nvm/versions/node/v6.10.1/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Line number out of range (line 4 requested, but only 3 lines present).
RangeError: Line number out of range (line 4 requested, but only 3 lines present).
```
#### And the status bar shows: 
Error: ESLint crashed: Line number out of range (line 4 requested, but only 3 lines present)

**Comment by cyberwombat** [comment]
This is a bug in ESLint that is resolve in 4.x https://github.com/eslint/eslint/issues/8401
Depending on how you use Eslint you might be able to upgrade. I use it as part of StandardJS and that is still in the works https://github.com/standard/standard/issues/925
