### ISSUE TITLE
Feature Request: eslint-plugin-json

### ISSUE THREAD

**Issue by richardpringle** [SublimeLinter/SublimeLinter-eslint#164]
Would love it if this also linted .json files with [eslint-plugin-json](github.com/azeemba/eslint-plugin-json) if the user has that plugin.

Happy to contribute, would need advising if this feature is approved though.

**Comment by richardpringle** [comment]
Nevermind on the advising, was easier than I thought.

**Comment by kaste** [comment]
Fixed by your PR.
