### ISSUE TITLE
Stuck on "There are no errors in console, but plugin does nothing."

### ISSUE THREAD

**Issue by eric-norcross** [SublimeLinter/SublimeLinter-eslint#167]
Followed the installation and troubleshooting guides, however I'm still stuck on "There are no errors in console, but plugin does nothing."

I'm using:
• node v8.1.3
• Sublime Text 3 build 3126
• SublimeLinter v3.8.0+1
• macOS v10.12.5
• eslint v3.19.0

In attempting to install this linter I have the following:
• I installed `eslint` locally with `$ npm install eslint --save-dev`
• I ran the init command with `$ ./node_modules/.bin/eslint --init`
• When running `$ ./node_modules/.bin/eslint src/App.js` from the console, the linter works properly
• I have a correctly configured `package.json` file in the project root
~~~~
{
  "name": "my-react-todolist",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "jest-cli": "^20.0.4",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts": "1.0.10"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0"
  },
  "peerDependencies": {
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0"
  }
}
~~~~
• I've restarted ST multiple times
• I'm seeing `SublimeLinter: eslint linter loaded` in my sublime text console output
• SublimeLinter is in `Debug Mode`
• The `eslint` linter is activated 
• I have a `.eslintrc.js` file which looks like this:
```
module.exports = {
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ]
};
```
• I'm using a `.sublime-project` file which is set as:

~~~~
{
  "folders": [
    {
      "path": "."
    }
  ],

  "SublimeLinter": {
    "linters": {
      "eslint": {
        "@disable": false,
        "args": [],
        "chdir": "${project}",
        "excludes": []
      }
    }
  },

  "syntax_override": {
    "\\.js$": ["TypeScript", "TypeScriptReact"]
  }
}

~~~~

What am I missing here?

**Comment by robwierzbowski** [comment]
I see you were using an .eslintrc.**js**: Sublime Linter didn't seem to be reading my .js rc file, but it did read the .json version. 

Just hit an issue where I need to use a .js. Did you ever figure this out / get Sublime to use your .js rc file?

**Comment by kaste** [comment]
This plugin was unmaintained in the last year.  It is now in the SublimeLinter org. Closing due to age of issue.
