### ISSUE TITLE
Sublime scrolls away when editor area clicked after eslint shows a message

### ISSUE THREAD

**Issue by mikemaccana** [SublimeLinter/SublimeLinter-eslint#168]
I save a file, Eslint shows an eslint message (great!) and scrolls to the problematic code in the middle of the editor area (great!)

I then click the editor area to fix the line and Sublime scrolls away - like about 10 lines. I don't know why.  

#### `SublimeLinter` console output

     SublimeLinter: eslint: index.js ['C:\\Users\\mike\\Documents\\myapp\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
     SublimeLinter: eslint output:
C:\Users\mike\Documents\myapp\routes\index.js: line 794, col 40, Warning - Use 'await' rather than using callbacks and then() (must-use-await/must-use-await)

     1 problem 

#### `eslint` output from command line

(Identical)

#### Additional info if needed (ST version, OS, configuration)

Windows 10, Sublime 3126.

**Comment by braver** [comment]
The way errors are shown has been completely revamped in SublimeLinter 4. The problem you described here couldn’t  be solved anyway, it’s an effect of how that feature works in ST.
