### ISSUE TITLE
HTML <script src=""></script> tag problem

### ISSUE THREAD

**Issue by littlee** [SublimeLinter/SublimeLinter-eslint#173]
the linter doesn't ignore the `<script src=""></script>` block

#### `SublimeLinter` console output
```
SublimeLinter: eslint: index.html ['/usr/local/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
/Users/xpg/project/my-vue/index.html: line 2, col 3, Error - Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag
```

#### `eslint` output from command line
```
➜  my-vue eslint index.html

/Users/xpg/project/my-vue/index.html
  1:2  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```

I want it to ignore the <script> block with src attribute in html files, thanks

**Comment by kaste** [comment]
Do you use vue here, or the eslint html plugin?

**Comment by littlee** [comment]
My old computer has broken, and I am using another editor now, maybe I could try the latest version of this package.
