### ISSUE TITLE
CPU at 100% when file is to big/complex

### ISSUE THREAD

**Issue by Kronuz** [SublimeLinter/SublimeLinter-eslint#175]
I'm getting 100% CPU usage (even after closing the file in Sublime Text, as the node process keeps running) for certain big JavaScript files after opening them.

My suggestion would be adding a setting to limit the size of a file being linted. If the edited file is larger than the given size in the settings, just ignore and do not lint, and/or kill process somehow when closing files.

**Comment by braver** [comment]
If such a setting is added, we'd do it as a core functionality.

https://github.com/SublimeLinter/SublimeLinter/issues/482
