### ISSUE TITLE
eslint not found when installed through WSL

### ISSUE THREAD

**Issue by CrshOverride** [SublimeLinter/SublimeLinter-eslint#179]
I'm currently using the WSL (Windows Subsystem for Linux) to build/run my React project. When trying to use the local instance of `eslint`, the plugin fails to find the executable.

#### `SublimeLinter` console output

```
SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
SublimeLinter: ERROR: eslint cannot locate 'eslint' 
```

#### `eslint` output from command line

Help: Use the same `eslint` instance which plugin uses (check console output). Run in terminal: 

No output (successfully linted the file)

#### Additional info if needed (ST version, OS, configuration)

If I run `npm install eslint` in Windows (without modifying anything else), linting works. It seems that the Windows `eslint` install creates both `eslint` and `eslint.cmd` executables on install. The plugin relies on `eslint.cmd` existing.

The plugin should be able to support running the binary directly (VSCode does exactly this) rather than depending on just the `.cmd`.

**Comment by braver** [comment]
If you use WSL to install executables, it will install those compiled for Linux. You cannot run these from the Windows desktop environment, it's not interoperable that way as far as I know?

**Comment by CrshOverride** [comment]
@braver I failed to check to see if `eslint` required native modules. If not, then it shouldn't be an issue.

**Comment by braver** [comment]
Good point. I think the problem lies here (and certainly not in SL-eslint):
https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/base_linter/node_linter.py#L163

If you want you could experiment with tweaking that bit of code. Perhaps it should attempt to run without the `.cmd` extension in this case.

**Comment by CrshOverride** [comment]
@braver I'll give it a shot shortly. Thanks for the input.

**Comment by kaste** [comment]
Please checkout https://github.com/SublimeLinter/SublimeLinter/pull/992 and comment if this works for you.

**Comment by kaste** [comment]
@CrshOverride Hi! Can you check out the PR https://github.com/SublimeLinter/SublimeLinter/pull/992

**Comment by kaste** [comment]
As for now you can do this manually. If we support this automatically, we'll see later.

**Comment by caylorme** [comment]
I have `node` and `eslint` installed in my WSL. I use `Sublime Text 3` within my Windows 10 host to modify my application, and typically run my builds / dev setup within WSL.
So, naturally, I would like for Sublime Text 3 to execute the WSL node and eslint.

I was able to accomplish this with a few modifications, and I'm hoping that it could help you.

**ESLint.py**
```
import re
```
I override the files slice with the following:
**@ EslintExecCommand().run():**
```javascript
files = [re.sub('([A-Z]):',lambda m: "/mnt/" + m.groups()[0].lower(),f).replace(os.path.normpath("/"),'/') for f in files]
```
This basically turns any `C:/Users/myUser/myProject/myfile.js` into `/mnt/c/Users/myUser/myProject/myfile.js`

I override `linter_path` ,`node_modules_path`, and `config_file` to their respective WSL equivilents, assuming though that we could run a similar sub on whatever/however those are derrived normally.

And finally, just add 'wsl' as the primary binary in `cmd`:
```
args = {
      'cmd': [
        'wsl',
        'node',
        linter_path,
        files[0],
        node_modules_path,
        config_file
      ],```

Let me know if this was helpful at all.

**Comment by kaste** [comment]
Hi @caylorme You're in the wrong repo/package. Here is SublimeLinter.

**Comment by caylorme** [comment]
@kaste I realize that now :)
I'm going to make similar modifications to this particular plugin and see how that goes.
I'm assuming this line: https://github.com/SublimeLinter/SublimeLinter-eslint/blob/master/linter.py#L26 is where I want to start. The "@" is the parameters (filenames?)

**Comment by kaste** [comment]
So, where is @caylorme? Jason? Jaaason.

**Comment by caylorme** [comment]
Hey hey!

**Comment by caylorme** [comment]
I ended up making changes to **TheSavior/ESLint-Formatter** since it provides `--fix` capabilities along with `format_on_save`
https://github.com/TheSavior/ESLint-Formatter/pull/63

feel free to use the toUnix() function from this to add support to your plugin.

**Comment by TheDirigible** [comment]
SublimeLinter is currently unusable when running Sublime Text in windows, for a filesystem in WSL.  Is there some workaround for this that I'm not aware of?
