### ISSUE TITLE
Linting PHP files does not work

### ISSUE THREAD

**Issue by ipkpjersi** [SublimeLinter/SublimeLinter-eslint#183]
I was instructed to post this here by sublimelinter: https://github.com/SublimeLinter/SublimeLinter3/issues/692

#### `SublimeLinter` console output

![](https://i.imgur.com/NXmWbvI.png)

#### `eslint` output from command line

https://hastebin.com/osotekeran.coffeescript

#### Additional info if needed (ST version, OS, configuration)

Here is my ESLintrc.js file: 

https://hastebin.com/ezasepohex.java

Sublime 3143, Ubuntu 16.04 LTS with Xfce. Using eslint v4.13.0, node v6.12.2, npm v3.10.10.

I have tried sublime linter eslint by roadhump and also by polygonplanet, neither have working linting for PHP files.

**Comment by kaste** [comment]
Closing here and instead reopening your original issue https://github.com/SublimeLinter/SublimeLinter/issues/692
