### ISSUE TITLE
'linebreak-style' rule errors are not shown

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter-eslint#184]
_(Using Sublime​Linter-contrib-eslint 1.10.0 and ESLint 4.13.1
with SublimeLinter 3.10.7 or 4.0.0-rc.12  
in ST3 3156 x64 )_

The issue is that [linebreak-style](https://eslint.org/docs/rules/linebreak-style) rule errors are not shown. 
For example, save the following code in a file,  using CRLF/Windows newlines:

```javascript
/*eslint linebreak-style: ["error", "unix"], "no-unused-vars": ["warn", {"vars": "all", "args": "after-used"}]*/ 

var a = 'a'; // \r\n
```

If you lint it with ESLint via the command prompt it shows:
![2017-12-20_014438](https://user-images.githubusercontent.com/723651/34184251-604ed238-e527-11e7-94af-4c71792b3ab2.jpg)

But, in ST it displays  only the `no-unused-vars` warning :
![2017-12-20_015511](https://user-images.githubusercontent.com/723651/34184519-dae244de-e528-11e7-8b1b-adb1b22c7225.jpg)

PS. For reference, in VSCode 1.19.0 with ESLint extension 1.4.3, 
the ''linebreak-style' rule errors are displayed, as well ([screenshot](https://user-images.githubusercontent.com/723651/34343567-21e00ee4-e9dd-11e7-9d2a-ffc347e3bdfa.jpg)).

**Comment by kaste** [comment]
Hi 👋 ! 

The plugin currently doesn't operate on the actual files but the Sublime Text buffer contents (via stdin) which have normalized line endings.
