### ISSUE TITLE
doesnt work with vue anymore

### ISSUE THREAD

**Issue by ctf0** [SublimeLinter/SublimeLinter-eslint#190]
for some time now vue files stopped being linted.

eslint: v4.17.0
eslint-plugin-vue: v4.2.2
STLinter: v3.10.9

**Comment by bblanchon** [comment]
I fixed the problem by changing "Vue Component" to lowercase:
https://github.com/SublimeLinter/SublimeLinter-eslint/blob/master/linter.py#L24

**Comment by braver** [comment]
Why is that in upper case? That don't work...

**Comment by ctf0** [comment]
@bblanchon nothing changed, i even have the below under st linter settings
```
"syntax_map": {
            "vue": "javascript",
            "vue component": "javascript"
        },
```
