### ISSUE TITLE
SublimeLinter-contrib-eslint not showing

### ISSUE THREAD

**Issue by defaultbr** [SublimeLinter/SublimeLinter-eslint#191]
i cant find the contrib at the package list:

Installed Packages
![image](https://user-images.githubusercontent.com/5432351/35836244-62746dce-0ac6-11e8-8600-6f26e33178fc.png)

to Install:

![image](https://user-images.githubusercontent.com/5432351/35836258-7748df32-0ac6-11e8-804f-f2dcc2c3bee3.png)

**Comment by braver** [comment]
There is no SublimeLinter-contrib-eslint. Why are you looking for it?

**Comment by defaultbr** [comment]
@braver owww, after you said that i started looking for other terms, and i found this one: https://github.com/SublimeLinter/SublimeLinter-eslint/issues/186

is that correct, thanks

**Comment by braver** [comment]
👍
