### ISSUE TITLE
Does this lint .js files or only .jsx files? 

### ISSUE THREAD

**Issue by jaepage** [SublimeLinter/SublimeLinter-eslint#192]
It seems to be ignoring my plain JS files (viewed as Babel JS in Sublime). Is that intended? Is that configurable? Or is it expected or recommended to use a separate JS linter? Thanks.

**Comment by kaste** [comment]
Ahem, eslint mainly lints '.js' files of course. Check your syntax and in the settings the `syntax_map`. The default here currently is/should be

```
    "syntax_map": {
        "html (django)": "html",
        "html (rails)": "html",
        "html 5": "html",
        "javascript (babel)": "javascript",
        "magicpython": "python",
        "php": "html",
        "python django": "python",
        "pythonimproved": "python"
    }
```

which basically means that `javascript (babel)` is a synonym for `javascript`

**Comment by Standard8** [comment]
You want to use an ESlint plugin for jsx files:

https://github.com/yannickcr/eslint-plugin-react

iirc, there's a setting to enable the sublime linter to run on jsx as well.

**Comment by jaepage** [comment]
Yes, my syntax map is unchanged: 
```
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
```

**Comment by jaepage** [comment]
The problem isn't lack of linting on JSX files by this package, it's lack linting on JS files.

**Comment by jaepage** [comment]
Why was this issue closed, please, when it's yet resolved?

**Comment by braver** [comment]
In it's default setup, eslint requires a config file. Did you set one up? You should turn on debug mode for SublimeLinter and look at the output to debug your setup, this doesn't sound like a general bug in this plugin.

**Comment by jaepage** [comment]
This plugin is linting without a custom config file, using its built-in default config. I'm aware I could create a `.eslintrc` file to customize the default rules, but what would I add to it to enable linting of `.js` files?

**Comment by braver** [comment]
> You should turn on debug mode for SublimeLinter and look at the output to debug your setup, this doesn't sound like a general bug in this plugin.
