### ISSUE TITLE
Is this expected?

### ISSUE THREAD

**Issue by Stockton-pr** [SublimeLinter/SublimeLinter-eslint#197]
Have these messages in ST(3) console running lint in debug mode, all else appears to run as expected:
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x268da70> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x268da70> 
Do i need to fix something?

ST 3154 Ubuntu 16.04 eslint 4.18.1 node 9.6

**Comment by kaste** [comment]
Yes, this is expected (although a bit ugly). This has been fixed for SL4 generally, also note #196

**Comment by Stockton-pr** [comment]
Ah ok thanks for this. Whilst here I have been trying to get the fix for hml plugin to work by updating and copypasta -ing but nothing works can you point me in the right direction?

**Comment by kaste** [comment]
Well, try SL4 and #196 😄 

Otherwise, delete

https://github.com/SublimeLinter/SublimeLinter-eslint/blob/34f1b74bc4b4b3513ec98eb0ae52bfccefb13b4d/linter.py#L44-L46

👿
