### ISSUE TITLE
cannot find sublimelinter-eslint in package-control 

### ISSUE THREAD

**Issue by grenudi** [SublimeLinter/SublimeLinter-eslint#199]
Am I doing something wrong ?

![image](https://user-images.githubusercontent.com/17498075/36667673-badc49ac-1aff-11e8-87f3-433385df12bb.png)
![image](https://user-images.githubusercontent.com/17498075/36667681-c38c5394-1aff-11e8-9103-1ed11de85e41.png)

**Comment by kaste** [comment]
Package Control is currently down.

**Comment by grenudi** [comment]
Oh, ok :(. And why there is no information about it on github README page ? It would be very useful, you know, I spent some effort before to create the issue. And it's mean that I have to plug it from source ?

**Comment by braver** [comment]
> And why there is no information about it on github README page

Because we maintain 47 repositories here, so we don't update our readme's to reflect the service status of a distribution method. Chill out and wait for package control to recover.

https://forum.sublimetext.com/t/announcement-package-control-degraded-functionality/35381/2

**Comment by grenudi** [comment]
Sorry, my bad.
