### ISSUE TITLE
Fixable warnings and errors

### ISSUE THREAD

**Issue by blake-regalia** [SublimeLinter/SublimeLinter-eslint#202]
Just wondering if its part of the plan for the sl4 branch to indicate in some way (e.g., using a wrench icon) if an error was produced by a fixable rule and thus is a fixable line?

**Comment by braver** [comment]
No, that's not in our current scope. We have warnings and errors and that's it. You can differentiate the icons for these 2 severity levels across specific linters, but it's not possible to introduce new levels. You could open an issue in the core SL repo to discuss this further.

**Comment by blake-regalia** [comment]
Are you sure about that? The reason I ask is because it seems SL4 will support this: https://raw.githubusercontent.com/SublimeLinter/SublimeLinter/master/messages/4.0.0-rc.1.txt

**Comment by braver** [comment]
Well that tells you how much I know, and I'm the guy who wrote that document. Go figure. Anyway, what you *can* do is assign different styles to error codes. So if you know what error codes are fixed by your linter, you can assign a style to that. Example using the Default gutter theme:

```json
{
    "scope": "variable.function",
    "priority": 1,
    "icon": "cog",
    "codes": ["D100"]
}
```

**Comment by kaste** [comment]
Closing *feat* requests that fast is already not welcoming (there are never in our scope anyway). And 'Go figure' was completely uncalled for @braver (unless you both are buddies 😄 ).

AFAIK the first (manual) approach here is indeed to customize your settings. `'codes': ['no-extra-semi',]` etc. Now the auto-fixable rules are of course a moving target.

Why do you want a special icon here, if these are auto-fixable, wouldn't it be better to not show them at all. (Just like if you use prettier, you sure turn off all the warnings, prettier already fixes for you.)

**Comment by braver** [comment]
Yeah, I did not have an excellent day yesterday. The "go figure" thing was meant as a stab at my own inability to remember how SublimeLinter works. So, sorry all around. 

We maybe need a place to describe tips and tricks like this. 

So, this discussion, if we're taking this any further, should be in the core repo.
