### ISSUE TITLE
Show errors on save

### ISSUE THREAD

**Issue by hungnt-me** [SublimeLinter/SublimeLinter-eslint#209]
My ST just upgraded to new version automatically and it doesn't prompt a dialog to display all eslint errors as before. Does anyone face this problem like me?

```
Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('show_errors_on_save' was unexpected)
```

**Comment by braver** [comment]
This feature was removed. More info and similar discussions over at the the core SublimeLinter repo.

**Comment by hungnt-me** [comment]
Thanks, now use keyboard shortcuts instead

<img width="923" alt="screen shot 2018-03-05 at 2 25 03 pm" src="https://user-images.githubusercontent.com/3900910/36962178-17d2cbaa-2081-11e8-8ac3-e6fda9df40ce.png">
