### ISSUE TITLE
Add option to report only the first token instead of the whole code block

### ISSUE THREAD

**Issue by dangh** [SublimeLinter/SublimeLinter-eslint#212]
Follow the conversation here https://github.com/SublimeLinter/SublimeLinter/issues/1105

Because SL has no idea about the code, should we introduce an option to report only the position of the first token when the error is multiple lines?

**Comment by shoebox639** [comment]
There are very legitimate uses of this. One that's really slowing me down right now involves `fdescribe` and `fit` for runnning single tests. When writing protractor (or any other slow running tests), it helps to only run the test that you care about when you are first writing it or debugging it. You Also don't want any of these tests to accidentally get committed and have your CI only run that one test.

Right now, the entire test (or suite) is outlined and it's very difficult on which to develop. Other more line specific linting errors are hard to see. See the following:

![image](https://user-images.githubusercontent.com/422974/37361845-3d14e822-26ca-11e8-896f-24caa049d64d.png)

Before, only the `fit` at the beginning of the test would be highlighted, allowing me to finish writing the rest of the test and then remove it before committing.

**Comment by polypodioides** [comment]
I would like to add that I'm using SublimeLinter-eslint to enforce style on my and other people's new code in a repository that's full of errors from previous developers. We can't do a global eslint fix for various reasons. The fact that this linter plugin is highlighting pretty much all code indiscriminately has destroyed our team's workflow in using eslint through Sublime. Without the option to disable this behavior, we will have to switch to something else entirely.

**Comment by eden-lane** [comment]
I've managed to disable this outline with the following config:
```
"styles": [
        {
            "mark_style": "none",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "circle",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "none",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "circle",
            "types": [
                "error"
            ]
        }
    ]
```

You can find this config in **Preferences - Package Settings - Sublime linter - Settings**

**Comment by polypodioides** [comment]
I appreciate the suggestion but I that doesn't solve my problem, it just hides the outline, which I had been using to find linter errors.

The reason I used a mark style to find errors is that I have other marks in the gutter that I would like to take priority, and previously, SublimeLinter-eslint was providing an outline around the exact region of the error. My issue is that the outlining behavior was changed with no way to set a configuration to limit the scope of the highlight.

**Comment by braver** [comment]
> a repository that's full of errors from previous developers

Well, you can use [project settings](http://www.sublimelinter.com/en/stable/settings.html#project) for that. 

You might also want to try the [demote white editing](https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L30) setting. It'll suppress the outlines when you're busy with the file, but they're there when you're done.

> which I had been using to find linter errors.

Even with the highlights suppressed visually, you can use the [output panel](https://github.com/SublimeLinter/SublimeLinter/blob/master/Default.sublime-commands#L7). It lists all errors in a way that let's you browse them easily.

Further discussion of this should go in https://github.com/SublimeLinter/SublimeLinter/issues/1171, as this is core functionality and not something specific to eslint.

**Comment by Slapbox** [comment]
Is there some way to leverage `demote_while_editing` to suppress all outlines, rather than just ones near where the cursor is? The idle time doesn't seem to be obeyed for me either, at least not consistently.

Is there no way to fallback to plain old underline, even if a limited version, rather than outline? I really do find it almost unusable. My linter didn't work for a day and that sucked. Now that I've got it back (with outlines) I'm wondering whether I'd be better off going back to no linter except for manual use. There's gotta be something... right?

**Comment by kaste** [comment]
@Slapbox You probably could use these settings 

```
	"highlights.demote_while_editing": "some_ws",  // or "multilines"
	"highlights.demote_scope": "",
	"highlights.time_to_idle": 3600,
```

'some_ws' will match all regions for which we apply the outline fallback.

@shoebox639 (and generally for specific annoying rules) you can use *linter* styles, like so:

```
{
    "linters": {
        "eslint": {
            "styles": [
                {
                    "codes": ["no-trailing-spaces"],  // a list of 'rules'
                    "mark_style": "none",
                    // and/or 
					"icon": "none"
                }
            ]
        }
    }
}
```

Maybe take a look at https://github.com/kaste/SublimeLinter-addon-filter for dynamic, ad-hoc filters.

**Comment by Slapbox** [comment]
Hm. Even though `some_ws` is listed as an option for the demote setting, it is not accepted and crashes the linter. I have to use `ws_regions`

This works partially at best, unfortunately. The whitespace regions don't disappear consistently or stay gone consistently.
