### ISSUE TITLE
Parsing json result fails if eslint outputs warnings

### ISSUE THREAD

**Issue by vegar** [SublimeLinter/SublimeLinter-eslint#214]
I posted first an issue in [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter/issues/1132), but it looks like an inprovement of SublimeLinter-eslint is whats needed.

Basically, eslint outputs some deprecation messages alongside the lint errors, which again breaks the parsing of the output.

```
[2018-03-06 16:16:42,979 - INFO     - SublimeLinter.lint.linter] eslint: cwd: C:\Source\flis
SublimeLinter: #15 SublimeLinter.sublime-package:809: eslint output:
    [{"filePath":"C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js","messages":[{"ruleId":"quotes","severity":2,"message":"Strings must use singlequote.","line":16,"column":17,"nodeType":"Literal","source":"      restrict: \"EA\",","endLine":16,"endColumn":21,"fix":{"range":[260,264],"text":"'EA'"}},{"ruleId":"no-multi-spaces","severity":2,"message":"Multiple spaces found before '}'.","line":24,"column":13,"nodeType":"Punctuator","source":"      }     })","fix":{"range":[482,487],"text":" "}},{"ruleId":"object-curly-newline","severity":2,"message":"Expected a line break before this closing brace.","line":24,"column":13,"nodeType":"ObjectExpression","source":"      }     })","fix":{"range":[487,487],"text":"\n"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":3,"fixableWarningCount":0,"source":"(function() {\n  'use strict';\n\n  DropdownButtonComponentCtrl.$inject = [];\n\n  function DropdownButtonComponentCtrl() {\n    var vm = this;\n\n    vm.$onInit = function() {\n\n    };\n  }\n\n  angular.module('finale')\n    .component('dropdownButton', {\n      restrict: \"EA\",\n\n      templateUrl: 'src/app/components/button/dropdown-button.component.html',\n      controller: 'DropdownButtonComponentCtrl',\n      transclude: true,\n      bindings: {\n        icon: '@',\n        items: '<'\n      }     })\n    .controller('DropdownButtonComponentCtrl', DropdownButtonComponentCtrl);\n}());\n"}]
    The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
```

Suggested solution is to break output on line feeds, parse first as json and treat the rest as warnings for the console.,

**Comment by kaste** [comment]
Can you please edit the description so it shows up formatted as code.

**Comment by kaste** [comment]
I already hate this fix before I wrote it. LOL. 

Can we just suppress these warnings via a command line switch? Bc we don't need them anyway.

**Comment by braver** [comment]
@kaste Good idea.

```
Handling warnings:
  --quiet                        Report errors only - default: false
  --max-warnings Int             Number of warnings to trigger nonzero exit code - default: -1
```

`--quiet` seems like it might do it

**Comment by kaste** [comment]
No, that refers to lint warnings. (Dunno why they have this switch.)

**Comment by braver** [comment]
Oh, that's stupid. I don't see anything else that's useful in their docs. Perhaps the warnings are in a different error stream? What happens if we use `STREAM_STDOUT` instead of both?

**Comment by FichteFoll** [comment]
The issue in OP can probably be triggered by using the eslint angular plugin and specifying this: https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/rules/service-name.md

Looking at stdout separately sounds like a good idea.

**Comment by vegar** [comment]
Found this thread: https://github.com/eslint/eslint/issues/3039

I'm tempted to reopen it. Having all deprecated rules set to disabled as a solution seems a little short sighted. I would like mye linting rules as is even though they will change in a future release...

**Comment by kaste** [comment]
Grr, FWIW if I use the 'rule' 'no-spacsed-func' I get 

```
'messages': [{'column': 1,
                'line': 1,
                'message': "Definition for rule 'no-spacsed-func' was not found",
                'nodeType': None,
                'ruleId': 'no-spacsed-func',
                'severity': 2,
```

t.i. just normal json back.

**Comment by kaste** [comment]
And if use and violate the clearly deprecated 'no-spaced-func' I get

```
[{'errorCount': 1,
  'filePath': 'D:\\maik.h\\src\\node-updater.js',
  'fixableErrorCount': 1,
  'fixableWarningCount': 0,
  'messages': [{'column': 1,
                'fix': {'range': [453, 454], 'text': ''},
                'line': 20,
                'message': 'Unexpected space between function name and paren.',
                'nodeType': 'CallExpression',
                'ruleId': 'no-spaced-func',
                'severity': 2,
                'source': 'Hello ()'}],
```

No deprecation warning.

**Comment by kaste** [comment]
I just looking for something simple to reproduce, then fix it, dammit!

**Comment by vegar** [comment]
The deprecation warning I get is for the before mentioned angular service-name rule.

**Comment by kaste** [comment]
Oh, these suckers, they just use `console.warn` https://github.com/Gillespie59/eslint-plugin-angular/blob/9d64ca19128ecba3c3025efd89c60a0568ec5d86/rules/service-name.js#L70-L74

whereby eslint has an API for that https://github.com/eslint/eslint/blob/66a1e9aa85c37c1d4430ad633d8354930c818796/lib/rules/no-spaced-func.js#L13-L27

**Comment by vegar** [comment]
So this is actually an eslint-plugin-angular-issue?

**Comment by vegar** [comment]
Looks a lot better.
Thanks!

**Comment by vegar** [comment]
> No, it's just they deprecate loudly whereby the eslint policy is to deprecate silently.

Looks like it's some kind of 'conditional deprecation', that might be a reason for why they've done it this way, maybe?
