### ISSUE TITLE
SublimeLinter-eslint throwing error most of the time on Windows since SL4

### ISSUE THREAD

**Issue by rmcauley** [SublimeLinter/SublimeLinter-eslint#216]
SublimeLinter pops up a console warning most of the time (but not always?) when trying to run.

Here's the console debug, files and paths renamed for project obscurity. :)

```
SublimeLinter: #7 SublimeLinter.sublime-package:1184: eslint: myComponent.jsx ['C:\\Users\\rmcauley\\Documents\\GitHub\\myProject\\node_modules\\.bin\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'C:\\Users\\rmcauley\\Documents\\GitHub\\myProject\\__tests__\\pages\\myPage\\components\\myComponent.jsx', '--config=C:\\Users\\rmcauley\\Documents\\GitHub\\myProject\\.eslintrc']
SublimeLinter: #7 SublimeLinter.sublime-package:1187: eslint: cwd: C:\Users\rmcauley\Documents\GitHub\myProject
SublimeLinter: #6 SublimeLinter.sublime-package:809: eslint output:
    eslint [options] file.js [file.js] [dir]

    Basic configuration:
    [[[[ snipped out eslint help ]]]]
SublimeLinter: #7 SublimeLinter.sublime-package:809: eslint output:
    SublimeLinter: #7 SublimeLinter.sublime-package:809: eslint output:
    [{"filePath":"C:\\Users\\rmcauley\\Documents\\GitHub\\myProject\\__tests__\\pages\\myPage\\components\\myComponent.jsx","messages":[],"errorCount":0,"warningCount":0}]
SublimeLinter: #7 SublimeLinter-eslint.sublime-package:56: eslint output:
[{'errorCount': 0,
  'filePath': 'C:\\Users\\rmcauley\\Documents\\GitHub\\myProject\\__tests__\\pages\\myPage\\components\\myComponent.jsx',
  'messages': [],
  'warningCount': 0}]
```

It doesn't appear based on the command line arguments given that any environment settings should affect this which is why I suspect it _might_ be different from #205.

I got SL-eslint  to run a few times with no issues, but then I open another file and I get the console warning popping up.

My SL4 config is bone stock - I have made no changes to it and provided no extra arguments.  For now I've just disabled eslint because it's simply not working.

Could it be that the filename is not being wrapped in `"` to be friendly to Windows command line arguments?

**Comment by rmcauley** [comment]
I forgot to note: I am running bone stock SL4 config - no extra eslint options are being specified.

**Comment by kaste** [comment]
You should provide a fuller debug here. For lint task '6' we actually don't see the cmd and cwd. \#205 is about osx with nvm. So for Windows we would have a different bug in any way. (Unless you use the fancy wsl subsytem.)

**Comment by rmcauley** [comment]
How can I get a fuller debug?  I have SL set to `debug: true`, and the only thing I removed from the log is the output from `eslint --help`.

**Comment by kaste** [comment]
Sorry, not 'fuller', just 'longer'. Every lint tasks starts with a greeting log message. Something along, 'eslint is now linting index.js' etc. and then stops with a crash LOL or the final output.

**Comment by rmcauley** [comment]
Hmm I do see that when it runs, and now I can't duplicate the problem.  :/

I re-open this issue if I can get it to reliably happen, and it includes the usual log lines that you pointed out.  Sorry for the trouble.
