### ISSUE TITLE
SublimeLinter ERROR: CMD.EXE was started with the above path as the current directory.  UNC paths are not supported.

### ISSUE THREAD

**Issue by plakhin** [SublimeLinter/SublimeLinter-eslint#217]
After updating to new version (4.0.5) of SublimeLinter and SublimeLinter-eslint (4.0.1) today I started to receive an error on start:
```
SublimeLinter: #4 eslint OrdersMap.vue ERROR:

 [{"filePath":"\\\\192.168.0.1\\htdocs\\resources\\assets\\js\\components\\OrdersMap.vue","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]
'\\192.168.0.1\htdocs'

CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

3 days ago, before update (not sure which version were used, but latest for that moment) everything was working fine. Eslint CLI works fine with this UNC path, SublimeLinter-php works fine with the same path.

**Comment by kaste** [comment]
Hi 👋 ! Please try out #218

**Comment by kaste** [comment]
Release 4.0.2 should contain the fix.

**Comment by plakhin** [comment]
Yes, 4.0.2 resolved the issue. Thanks!
