### ISSUE TITLE
"Invalid settings" error on loading Sublime Linter 4 "shell_timeout was unexpected" after silent upgrade to 4.0.5

### ISSUE THREAD

**Issue by Shelagh-Lewins** [SublimeLinter/SublimeLinter-eslint#219]
Sublime Linter 4 was working yesterday but today I opened Sublime Text to the same project, and saw an error:

```
SublimeLinter: ERROR:

 Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('shell_timeout' was unexpected)
```
I haven't modified the user settings file but it looks like Sublime Linter has silently upgraded itself, the package is now listed as 4.0.5. Yesterday it was 4.0.3. I haven't received any notification via package control.

Has there been another change to the settings file format or is this a bug? Should I remove the setting?

**Comment by braver** [comment]
Yes, you should remove the setting. It had no implementation. 

I’ll add messages about such removals in the future (although I don’t expect any).

FYI in general you don’t need to copy settings to your user settings if you change them from the defaults.

**Comment by Shelagh-Lewins** [comment]
OK thanks!
