### ISSUE TITLE
eslint-plugin-vue stoped working after updating

### ISSUE THREAD

**Issue by plakhin** [SublimeLinter/SublimeLinter-eslint#221]
After updating to new version (4.0.6) of SublimeLinter and SublimeLinter-eslint (4.0.2) eslint-plugin-vue stopped showing errors and warnings. Eslint CLI works fine, SublimeLinter-eslint shows errors and warnings for rules configured in .eslintrc.json but none for rules in "plugin:vue/recommended".

**Comment by kaste** [comment]
Enable debug mode for SublimeLinter and look (maybe post) the console log messages. Esp. look for the `cmd` SublimeLinter actually executes and the working dir `cwd`.

**Comment by plakhin** [comment]
I've enabled debug mode in user settings and this is what I get in console:
```
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.6
SublimeLinter: SublimeLinter.sublime-package:256: detected syntax: javascript
SublimeLinter: #1 SublimeLinter.sublime-package:782: 'eslint' is linting 'FormsReview.vue'
SublimeLinter: #1 SublimeLinter.sublime-package:103: PATH:
    C:\Windows\system32
    ...
SublimeLinter: #1 SublimeLinter.sublime-package:1186: eslint: FormsReview.vue ['C:\\Users\\stan\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', '\\\\192.168.0.1\\htdocs\\resources\\assets\\js\\components\\FormsReview.vue']
SublimeLinter: #1 SublimeLinter.sublime-package:1189: eslint: cwd: \\192.168.0.1\htdocs
SublimeLinter: #1 SublimeLinter.sublime-package:809: eslint output:
    [{"filePath":"\\\\192.168.0.1\\htdocs\\resources\\assets\\js\\components\\FormsReview.vue","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]
    '\\192.168.0.1\htdocs'
    CMD.EXE was started with the above path as the current directory.
    UNC paths are not supported.  Defaulting to Windows directory.
SublimeLinter: #1 SublimeLinter-eslint.sublime-package:60: eslint output:
[{'errorCount': 0,
  'filePath': '\\\\192.168.0.1\\htdocs\\resources\\assets\\js\\components\\FormsReview.vue',
  'fixableErrorCount': 0,
  'fixableWarningCount': 0,
  'messages': [],
  'warningCount': 0}]
````

**Comment by kaste** [comment]
Did you read it?

> cwd: \\192.168.0.1\htdocs

> CMD.EXE was started with the above path as the current directory.
    UNC paths are not supported.  Defaulting to Windows directory.

**Comment by kaste** [comment]
Too fast, you could try to set `'working_dir': 'your/path'` in the eslint linter settings

**Comment by plakhin** [comment]
> Did you read it?

Yes, this is what I was reporting in #217, but after updating to 4.0.2 linting started to work (except eslint-vue-plugin). Eslint CLI works fine with this path, eslint in sublime takes config from `C:\users\stan\.eslintrc.json` (double checked) and lints common rules, but not vue.

I can not set working dir in config cause I've got several project which I'm working on simultaneously.

**Comment by kaste** [comment]
Haha, I thought I know you but didn't find it.

You can configure SublimeLinter in project settings.

You can also set which config file eslint should use using the args settings.

**Comment by plakhin** [comment]
> You can configure SublimeLinter in project settings.

Ok, will try it. Thanks.
But this looks like a workaround, not a solution.

**Comment by kaste** [comment]
But that's a warning from CMD.exe 

Maybe you can map that UNC to a folder?

**Comment by plakhin** [comment]
> Maybe you can map that UNC to a folder?
Just remembered that did it on a laptop yesterday. And the same problem there. Will paste debug info in several minutes.

**Comment by plakhin** [comment]
Ok, here is console output without UNC Paths:
```
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.6
SublimeLinter: SublimeLinter.sublime-package:256: detected syntax: javascript
SublimeLinter: #1 SublimeLinter.sublime-package:782: 'eslint' is linting 'FormsReview.vue'
SublimeLinter: #1 SublimeLinter.sublime-package:103: PATH:
    C:\Windows\system32
    ...
SublimeLinter: #1 SublimeLinter.sublime-package:1186: eslint: FormsReview.vue ['C:\\Users\\stan\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'Z:\\mda.local\\resources\\assets\\js\\components\\FormsReview.vue']
SublimeLinter: #1 SublimeLinter.sublime-package:1189: eslint: cwd: Z:\mda.local
SublimeLinter: #1 SublimeLinter.sublime-package:809: eslint output:
    [{"filePath":"Z:\\mda.local\\resources\\assets\\js\\components\\FormsReview.vue","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]
SublimeLinter: #1 SublimeLinter-eslint.sublime-package:60: eslint output:
[{'errorCount': 0,
  'filePath': 'Z:\\mda.local\\resources\\assets\\js\\components\\FormsReview.vue',
  'fixableErrorCount': 0,
  'fixableWarningCount': 0,
  'messages': [],
  'warningCount': 0}]
```

Once again, I can see errors and warning in this file for common JS rules configured in .eslintrc.json, but none of rules from "plugin:vue/recommended"

**Comment by plakhin** [comment]
And here is the output of eslint CLI:
```
C:\Users\stan>eslint z:\mda.local\resources\assets\js\components\FormsReview.vue

z:\mda.local\resources\assets\js\components\FormsReview.vue
  15:25  error  Elements in iteration expect to have 'v-bind:key' directives  vue/require-v-for-key

✖ 1 problem (1 error, 0 warnings)
```

**Comment by kaste** [comment]
But you're on a different working dir when on the CLI.

You must start eslint from z:// and use print-config or something like that to see what config file eslint automatically finds for you.

**Comment by plakhin** [comment]
```
C:\Users\stan>z:

Z:\>eslint mda.local\resources\assets\js\components\FormsReview.vue

Z:\mda.local\resources\assets\js\components\FormsReview.vue
  15:25  error  Elements in iteration expect to have 'v-bind:key' directives  vue/require-v-for-key

✖ 1 problem (1 error, 0 warnings)
```

`eslint --print-config mda.local\resources\assets\js\components\FormsReview.vue` output is too long to paste here. Which part I should be interested in and how can I check config used in Sublime?

**Comment by kaste** [comment]
So, how is it going?

I see you literally used `z:\` as cwd although SublimeLinter uses `Z:\mda.local`, why is that?

**Comment by plakhin** [comment]
> So, how is it going?

Nothing new to report :(

> I see you literally used `z:\` as cwd although SublimeLinter uses `Z:\mda.local`, why is that?

Just didn't `cd` into `mda.local`. But this doesn't matter, tried both ways just in case.

**Comment by kaste** [comment]
A success would be to recreate the behavior you're seeing in SublimeLinter on the CLI.

**Comment by plakhin** [comment]
Not sure how to do it

**Comment by kaste** [comment]
Now, this issue seems to be sitting around. I'm closing bc it is not likely to become an actionable issue. That doesn't mean we can't discuss it further.

**Comment by RichAyotte** [comment]
@plakhin The [ESLint](https://packagecontrol.io/packages/ESLint) package caused this issue for me. To fix, I uninstalled both ESlint and SublimeLinter-eslint and re-installed just SublimeLinter-eslint.
