### ISSUE TITLE
Prevent it from always linting the current view?

### ISSUE THREAD

**Issue by woojoo666** [SublimeLinter/SublimeLinter-eslint#224]
It looks like in the recent update of eslint, "the linter is trying to always lint the current view, even if there is no eslint setup for the project or file.". The README recommends just adding a .eslintrc file to your home directory to prevent the "no config file" error, but what if I want to go back to the old style of only linting project directories? Currently I have a 4000 line file and every time I save, it tries to lint the entire thing, and spikes my CPU usage to 100%. This is pretty annoying, and I might just uninstall eslint altogether. Any alternatives?

**Comment by kaste** [comment]
I don't remember this 'old style' actually. I know that the 'old' style was to eat most crashes. 

AFAIK you could exclude that file via the settings, otherwise, there *will* be a command to disable linting for the current buffer.

**Comment by woojoo666** [comment]
All I know is that I wasn't having problems before the update, and in the README for eslint, it says "If using SublimeLinter 4, the linter is trying to always lint the current view". It sounds like before we needed to explicitly include projects to be linted, but now we need to explicitly exclude projects. I think I prefer explicitly including projects, but I can see arguments for either way. I hope that there will be a way to switch between the two in the future.

**Comment by braver** [comment]
Have you tried setting eslint to “disable”: true in your user settings and then enabling it in project settings? At least that seems like what you’re trying to do?

**Comment by woojoo666** [comment]
hmm, that seems to work, though it requires me making a sublime settings file. I think originally all I had to do was make a .eslintrc file to enable linting of the current folder, but that's not a big deal.

I'm trying a few methods actually to see which I like best, but I can't seem to figure out how to configure file exclusion. Do I have to use the "excludes" pattern in the sublime linter settings, or can I do it using the .eslintrc file? There seems to be an "overrides" option in .eslintrc, not sure if that's relevant

**Comment by braver** [comment]
For excludes it’s important to know that SublimeLinter doesn’t just lint files on disk, but also modified buffers. Excludes in linter configuration, based on file name patterns, don’t work in that case. So that’s what the excludes in SL settings are for. Depending on your setup you may need to set ignores in both the eslintrc and SL.

**Comment by woojoo666** [comment]
do you know how to specify an exclude in the eslintrc file? I tried using the "excludedFiles" and "excludes" option and neither worked. Was I supposed to put it under "rules"? Also, is it possible to use the "disable" option in eslintrc? I'm fine with SublimeLinter linting buffers, I just want to do everything in the eslintrc files and not have to deal with creating sublime projects.

**Comment by braver** [comment]
Nope, don't write plain old JS enough to tell you more really.

**Comment by kaste** [comment]
See https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories for the eslint config.

**Comment by kaste** [comment]
Closing bc it's probably not an issue with this plugin. (We can re-open later if it turns out to be an issue.)

**Comment by woojoo666** [comment]
Thanks @kaste , that guide was all I needed! I was able to create a whitelist by first blacklisting all files in the global .eslintignore file, and then creating empty .eslintignore files in the directories that I wanted to whitelist. I think the only difference now is that eslint will always lint unsaved buffers, but I'm ok with that

**Comment by kaste** [comment]
FWIW, you can exclude unsaved buffers

```
"linters": {
     "eslint": {
         "excludes": [
            "<unsaved>"
         ]
     },
```

In that same setting you can also set `"!${folder}*"` (a negative exclude 😵 ) so it will only lint files contained in an open folder (usually a project) in Sublime.

**Comment by woojoo666** [comment]
awesome, thanks!
