### ISSUE TITLE
Linter not working at all, error on install

### ISSUE THREAD

**Issue by tonylukasavage** [SublimeLinter/SublimeLinter-eslint#229]
Sublime Text: 3.0, build 3143
eslint: 4.18.2

When I install Sublimelinter-eslint I get the following error (after multiple re-install attempts as well):)

```
ignored packages updated to: ["Makefile", "SublimeLinter-eslint", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Makefile", "Vintage"]
reloading plugin SublimeLinter-eslint.linter
SublimeLinter: ERROR: eslint disabled, not fully implemented 
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

```

the linter operates in no way, no error annotations or options in any of the menus. It's as if it doesn't exist. I have installed eslint locally, and i have tested it directly, meaning executing it from the command line. Using eslint directly works as expected. I also have a `.eslintrc.js` file. It was working on my computer for a long time, for all my repos, and suddenly stopped. I'm not sure if there was an update or something that knocked it out of commission, but it works on none of my repos now.

**Comment by kaste** [comment]
You're probably not on the latest version 4 of SublimeLinter

**Comment by dndrsn** [comment]
I downgraded to SublimeLinter v3 -- primarily because I much prefer the old behavior related to these two issues...

https://github.com/SublimeLinter/SublimeLinter/issues/1171
https://github.com/SublimeLinter/SublimeLinter/issues/1034

Looks like the latest version of SublimeLinter-eslint isn't compatible.  Am I correct in assuming 1.10.1 is the last compatible version?

**Comment by braver** [comment]
That's probably correct.

Assuming the OP is also resolved by now.
