### ISSUE TITLE
Empty, unsaved files open popup window

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter-eslint#230]
If we don't send any code via STDIN, eslint shows the help message. 😖

**Comment by braver** [comment]
I don't have this problem actually (eslint `v4.11.0`). What exactly happens in your case?

**Comment by kaste** [comment]
![image](https://user-images.githubusercontent.com/8558/37646523-33a36ccc-2c2a-11e8-9f28-59385881b9de.png)

**Comment by braver** [comment]
Ah, that's bad. Better merge that fix then!
