### ISSUE TITLE
Linter Error

### ISSUE THREAD

**Issue by Kotzilla** [SublimeLinter/SublimeLinter-eslint#232]
> SublimeLinter: #1 eslint file.js ERROR:   
> env: node: No such file or directory
> 

but i already set env and path to excute node

OSX, Sublimelinter eslint v4.0.4

**Comment by kaste** [comment]
You should find a lot of info in #205

**Comment by Kotzilla** [comment]
Thank you @kaste i'll take a look into it

**Comment by kaste** [comment]
We have a PR at https://github.com/SublimeLinter/SublimeLinter/pull/1266 to solve this issue automatically. Please check it.
