### ISSUE TITLE
How to set "rulePaths"

### ISSUE THREAD

**Issue by rhpijnacker** [SublimeLinter/SublimeLinter-eslint#235]
We have some custom rules that we want linted too. In our Grunt integration, we can set the "rulePaths" property to point to the right folder. 
How should I set this with the SublimeLinter-eslint plugin?

**Comment by kaste** [comment]
Hi :wave:

The command line option for that is named '--rulesdir'. You must set this manually using the `args` setting. http://www.sublimelinter.com/en/stable/linter_settings.html#args

**Comment by rhpijnacker** [comment]
Hi Kaste,

Thanks for the response. When I add 
```
// SublimeLinter Settings - User
{
    "args": "--rulesdir=../../Technology//eslint-iscv-custom-rules"
}
```
then the console says:
```
SublimeLinter: ERROR:

 Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('args' was unexpected)
```
so I do not think I'm doing it right yet.

**Comment by kaste** [comment]
That's not a global setting, you must add it to the linter section.

**Comment by rhpijnacker** [comment]
Ah, that helps  : ) .
Next problem: it does not seem to resolve the relative path correctly. The ../../ part seems to just be skipped.

**Comment by kaste** [comment]
It would be better if you try this first at the CLI level to find out to which folder these paths are relative.

**Comment by kaste** [comment]
Enable debug mode and look for the `cmd` it actually executes, and `cwd` the working dir.

**Comment by rhpijnacker** [comment]
Thanks for the pointers. I do not currently have the time to figure out how to enable the debug mode, will look at that over the weekend.
One thing I did notice: the relative path is being applied, but relative to the directory of the linted file.
So depending on how deep the file is in the directory structure it will try to look for the rules dir in a different place.
I expected this to be relative to the .eslintrc.json (like it is in the Grunt integration).

**Comment by kaste** [comment]
Closing bc unlikely to become an actionable issue.

**Comment by rhpijnacker** [comment]
The issue is not with eslint, as far as I can see. When using eslint directly, it works just fine. Also when integrated using the grunt-eslint we do not see any problems.
