### ISSUE TITLE
Cannot stop jshint from linting alongside eslint.

### ISSUE THREAD

**Issue by shamilovtim** [SublimeLinter/SublimeLinter-eslint#237]
I can find no way of stopping jshint from running amok and linting files I'm using with eslint.  Even when I disabled sublimelinter-jshint in package control, it somehow still is linting alongside eslint at the same time.

![screen shot 2018-03-24 at 4 24 23 pm](https://user-images.githubusercontent.com/3495974/37868615-d5f157b6-2f7f-11e8-88ea-4c89d8c86c2e.png)

**Comment by braver** [comment]
If you disable the package in package control, the plugin is still registered with SL. You can disable plugins on the fly using the the “disable” linter setting.

**Comment by shamilovtim** [comment]
Thank you!
