### ISSUE TITLE
error name doesn't appear in bottom bar

### ISSUE THREAD

**Issue by xShirase** [SublimeLinter/SublimeLinter-eslint#238]
After getting nvm/eslint to play nice with SL4, I noticed that the error name doesn't appear in the bottom bar anymore. I used this feature a lot to toggle/google rules by name directly. is there a way to have it back?

**Comment by kaste** [comment]
Look in the settings. Iirc there is template for that.

It is IMHO more convenient to open the error panel. Then select and copy paste the error.

**Comment by kaste** [comment]
Lackofresponseclosing
