### ISSUE TITLE
Single file vue components no longer work

### ISSUE THREAD

**Issue by SneakyMax** [SublimeLinter/SublimeLinter-eslint#239]
Single-file Vue components no longer work. I'm guessing it's related to https://github.com/SublimeLinter/SublimeLinter/issues/691?

Adding this to my `SublimeLinter.sublime-settings` fixes the issue, so that the whole file is sent to ESLint:

```
"linters": {
    "eslint": {
        "selector": "source.js, text.html.vue"
    }
}
```

Maybe that could be added to the defaults for SublimeLinter-eslint?

**Comment by braver** [comment]
Sending the whole file to eslint probably only works with a vue plugin for eslint. We don't expect such plugins by default. Instead we try to send the embedded javascript to eslint using the source.js selector. How well that works depends on the quality of the syntax, but it's the right approach at least and *should work* with vue as well.

So, if you're using an eslint plugin so you can send it the the entire vue file, the correct approach would be to change the settings as you did.

**Comment by braver** [comment]
- Do you use an eslint plugin for vue?
- What package are you using for the syntax highlighting?

**Comment by SneakyMax** [comment]
1. Yeah the normal `eslint-plugin-vue`
2. `Vue Syntax Highlight` (syntax called `Vue Component`)

I guess my main point is: "used to work, now doesn't". If you don't think it's in the scope of SublimeLinter-eslint any more, that's fine, it'll be documented here at least.

**Comment by braver** [comment]
Thanks. I'll look at it later, perhaps we can make it work out of the box again.

**Comment by braver** [comment]
Ok, so I had a look. 

- Without `eslint-plugin-vue` installed and configured, and without the `text.html.vue` selector, eslint does a halfway decent job of linting the javascript in a vue component.
- Without `eslint-plugin-vue` installed and configured, but **with** the `text.html.vue` selector, it's completely useless.
- If you do all the setup required for `eslint-plugin-vue`, including adding the selector for the SL plugin, it's 🎉 

So, I won't add `text.html.vue` by default, but will make a note about it in the readme etc.

**Comment by kevinmpowell** [comment]
> Without eslint-plugin-vue installed and configured, and without the text.html.vue selector, eslint does a halfway decent job of linting _the javascript_ in a vue component.

What about the `<template>` portion of the `*.vue` file? I'm getting linter errors in my console for `<template>` syntax issues, but no highlighting in SublimeText. I *do* get highlighting in SublimeText for the JS portion of the `*.vue` file.

I've added the `text.html.vue` selector in my preferences and `eslint-plugin-vue` is set up correctly.

Will this linter be able to show me errors for the `<template>` section? Or is that outside the scope of what this package can do?

**Comment by braver** [comment]
The selector decides what to send to the linter, so if `text.html.vue` covers the template section that should work.
