### ISSUE TITLE
Problem with hover window

### ISSUE THREAD

**Issue by Dave3of5** [SublimeLinter/SublimeLinter-eslint#243]
I'm getting the following problem with the hover window:

![screenshot](https://user-images.githubusercontent.com/13622748/39566762-927e1862-4eb4-11e8-9759-07f00cd74180.png)

No errors in the console. Anyone any idea what's causing this ?

**Comment by braver** [comment]
You're getting the definitions popup on hover. There is no way for one package's popup to take precedence over another or to toggle between different popups. We can't fix this. Options:

- disable the definitions popup
- trigger the SublimeLinter line report to view our popup

**Comment by Dave3of5** [comment]
@braver Thanks for the response I'm quite a sublime newbie I'm not sure about your options what are the consequences of each? How do I actually do them as I don't believe I have installed a package called definitions.

**Comment by braver** [comment]
The definitions are a default feature of Sublime Text. You can disable them with the `"show_definitions"` setting. You won't be able to get that popup anymore though.

The line report is show when triggering the "SublimeLinter: Show Line Errors" command via the command palette.

**Comment by Dave3of5** [comment]
Awesome changing that settings has helped, I don't think I'd ever use the show definitions feature anyway.

**Comment by braver** [comment]
👍
