### ISSUE TITLE
Deprecation warnings keep popping up

### ISSUE THREAD

**Issue by brettimus** [SublimeLinter/SublimeLinter-eslint#244]
Hey! So this is more than likely PEBCAK, but I haven't found a setting that can quiet these deprecation warnings that keep popping up at the bottom of my window. See:

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/3201327/39617608-9f9eb02a-4f80-11e8-8271-885842ba2ad0.png">

This feels vaguely related to discussion on #214, which points to #218 for a solution. I didn't find anything in there that could get the logs to stop 🍿 popping up. 

My quick fix was just to delete the deprecated configuration setting from those dependencies, react and react-a11y. (Yeah yeah, I know I know.) I was hesitant to file issues on the repo bc I need to get some work done today too 😁 , but would be happy to do that as well if that's what you think the best path is. 

For reference: I'm using the latest version of the airbnb style guide, so this seems like it could potentially be affecting a good chunk of people.

**Comment by kaste** [comment]
Probably update airbnb?

**Comment by brettimus** [comment]
Looks like v4.19.1 of eslint, and I just realized that although airbnb was listed as latest in our package.json, our yarn lock file had a super outdated version. 

sorry for the noise! closing
