### ISSUE TITLE
[docs] Inline JavaScript in Vue single-file component templates tags being treated is individual files

### ISSUE THREAD

**Issue by jwkicklighter** [SublimeLinter/SublimeLinter-eslint#246]
This is sort of weird and hard to explain in one line, so I hope the title makes sense. It also seems to be a different issue than I have already seen for Vue files.

ESLint is linting `.vue` files just fine for every case except one. I have the `eol-last` rule enabled (to require a newline at the end of files). This is causing a problem within the `<template>` section of `.vue` files where every single piece of inline JS is being treated as an individual file, meaning that they all show an error for this rule.

See the file below for a small example of the issue. Every one of the errors in the gutter is this rule being triggered.

<img width="787" alt="screen shot 2018-05-11 at 17 09 59" src="https://user-images.githubusercontent.com/1447947/39946962-3076b936-553e-11e8-82dd-1a5daaaa567f.png">

**Comment by jwkicklighter** [comment]
@kaste I have, and it does the same behavior with or without that section of the settings file.

**Comment by jwkicklighter** [comment]
I was adding these settings to the overall settings file and not the SublimeLinter-specific file... Totally my mistake, but I'm wondering if we could improve the docs to mention that. Just a couple words in the section that you linked would be enough to help.

Or maybe I'm the only person that's done this :)

**Comment by braver** [comment]
@jwkicklighter Have you got this working correctly now?

**Comment by jwkicklighter** [comment]
@braver I do, didn't close the issue because I was considering making a PR to improve the docs slightly.

**Comment by braver** [comment]
👍🏻

**Comment by kaste** [comment]
Closing, no need to wait for a PR any longer.

**Comment by jwkicklighter** [comment]
I completely forgot about this issue
