### ISSUE TITLE
White highlight

### ISSUE THREAD

**Issue by OoDeLally** [SublimeLinter/SublimeLinter-eslint#248]
Since a few weeks ago, yellow (warning) and red (error) highlights have both been replaced by a white highlight. 
e.g.
![image](https://user-images.githubusercontent.com/1717629/39997896-b1e119ba-5784-11e8-8623-40736b819262.png)
I am not sure which package is responsible for picking the highlight color. Please correct me if that's not done by this package.
How can I get those colors back?

**Comment by kaste** [comment]
Ensure you have Sublime Text 3.1, then look here http://sublimelinter.readthedocs.io/en/stable/settings.html#styles-colors and https://www.sublimetext.com/docs/3/color_schemes.html#customization

**Comment by kaste** [comment]
The defaults require a newer ST version. Either update ST or hack your theme.

**Comment by OoDeLally** [comment]
That was it! I thought build 3126 means 3.1. I guess 3126 was a beta version.
Problem solved, thank you!
