### ISSUE TITLE
Highlighted error in wrong position

### ISSUE THREAD

**Issue by jgbishop** [SublimeLinter/SublimeLinter-eslint#249]
I'm seeing an offset bug with the highlighting in eslint in Sublime 3.1.1:

![bug](https://user-images.githubusercontent.com/4210087/40015342-09a98e24-5781-11e8-8a62-85ce5660d478.png)

The error boxes should be around the variable names, but they appear to be shifted by 4 characters. I'm not real sure who is to blame here (SublimeLinter or this plugin), so I'm starting here first.

The code shown in the screenshot above resides in an HTML file that uses 4 spaces as the indentation width. When I convert to tabs, the rectangles are still misaligned, but only by 1 character. I also note that this affects squiggly underlined areas too (I see both in the same file, for reasons unknown to me).

I'm running SublimeLinter 4.5.1 and SublimeLinter-eslint 4.1.1 on Windows 10. I also use the flake8 linter, and it doesn't appear to have this problem.

**Comment by kaste** [comment]
They changed the selector. 💩 

Sublime 3.1.1

![image](https://user-images.githubusercontent.com/8558/40016629-37993614-57b7-11e8-99d2-8145517ca1aa.png)


Sublime 3.0

![image](https://user-images.githubusercontent.com/8558/40016673-5d4316a0-57b7-11e8-8962-9fd01b29aeb5.png)

**Comment by kaste** [comment]
Changed my mind: PR is at https://github.com/SublimeLinter/SublimeLinter/pull/1406
