### ISSUE TITLE
eslint output appears in panel, not gutter

### ISSUE THREAD

**Issue by greveritt** [SublimeLinter/SublimeLinter-eslint#251]
Hello everyone,

I am using the latest build of Sublime Text 3.1.1 on macOS High Sierra, and I am no longer seeing eslint output in the gutter; I only see the JSON output in the same warning panel that used to hold Deprecation and Experimental Warnings. I have copied an anonymized version of an eslint "error" that I found in this panel after deliberately messing up a symbol name, and I will paste it below. 

```
SublimeLinter: #6 eslint CLASS_NAME.js ERROR:
====================================================

eslint output:
PROJECT_PATH/config/webpack/loaders
[{"filePath":"PROJECT_PATH/SOURCE_PATH/CLASS_NAME.js","messages":[{"ruleId":"no-undef","severity":2,"message":"'VARIABLE_NAME' is not defined.","line":34,"column":31,"nodeType":"Identifier","source":"REDACTED","endLine":34,"endColumn":44},{"ruleId":"react/jsx-curly-spacing","severity":2,"message":"There should be no space before '}'","line":34,"column":45,"nodeType":"JSXExpressionContainer","source":"REDACTED","fix":{"range":[946,947],"text":""}}],"errorCount":2,"warningCount":0,"fixableErrorCount":1,"fixableWarningCount":0,"source":"REDACTED"}]
```

Please let me know if there is any more information you need. Thank you for your time.

**Comment by kaste** [comment]
Hi!

(That's a horrible error message, really)

So what's happening here? We expect json from `eslint` and this message actually is a JSON decode error. (LOL, yeah!)

As you can see, you have 

> PROJECT_PATH/config/webpack/loaders

in the output. This additonal log/info probably doesn't come from eslint and corrupts the output.

**Comment by greveritt** [comment]
How odd. Perhaps someone changed our project's yarn or webpack configurations in a way that broke things? I may have to show them this thread when we return to work on Monday.

Do you have any tips on debugging this? Thank you.

**Comment by kaste** [comment]
If I know something worked last week I probably would use git bisect.

So it seems someone forgot to remove a console.log somewhere. These days eslintrc can be a normal js file, and of course you can have self-made plugins which are ordinary js itself. So I would look into these files.

**Comment by greveritt** [comment]
Thanks a million! Here is the message I got when I opened Sublime Text this morning. Please note that the first error message, the `AttributeError` one, only occurred once.

I removed the offending call to `console.log()` from our configuration and now everything works great. I'm going to have to remember to donate to SublimeLinter. 😁 

```SublimeLinter: #1 eslint SOURCE_FILE.js ERROR:
====================================================

Linter crashed.

Traceback (most recent call last):
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 761, in lint
    return self.parse_output(output, virtual_view)
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 778, in parse_output
    self.on_stderr(stderr)
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package/linter.py", line 47, in on_stderr
AttributeError: 'NoneType' object has no attribute 'warning'


SublimeLinter: #2 eslint SOURCE_FILE.js ERROR:
====================================================

JSON Decode error: We expected JSON from 'eslint', but instead got this:
PROJECT_PATH/config/webpack/loaders
[{"filePath":"PROJECT_PATH/app/javascript/components/press/SOURCE_FILE.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]


Be aware to not log additional info to stdout.
```

**Comment by greveritt** [comment]
I censored personal and project details before posting the message. It did not actually print `~/Library`; instead it printed out the absolute path. Hopefully I didn't make things confusing there.

**Comment by kaste** [comment]
Thanks for reporting the `AttributeError`. So what's happening here? You received an update while SublimeLinter was actually already linting some files. Bc we live-reload, running threads become orphaned and crash. I file an issue upstream.
