### ISSUE TITLE
eslint output not properly parsed in windows

### ISSUE THREAD

**Issue by jackysee** [SublimeLinter/SublimeLinter-eslint#262]
Environment: Windows 10 / SublimeText 3.1.1 / node 10.11.0 / eslint 5.6.1

The eslint error pop out in console:
```
SublimeLinter: #3 eslint index.js ERROR:
========================================

JSON Decode error: We expected JSON from 'eslint', but instead got this:
applying source-map option: eval-source-map

[{"filePath":"C:\\workspace\\MY-APP\\src\\index.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]


Be aware that we only parse the last line of above output.
```
This is due to the fact that my `.eslintrc.js` would call do `console.log` to have some debug message, so it prints the first line `applying source-map option: eval-source-map`. 

According to #251,  it should be fixed by reading only the last line. So the problem seems to be that the line `output.rstrip().split(os.linesep)[-1]` in `linter.py` is cannot split the output. 

I have tried to locally changed it to `output.rstrip().split('\n')[-1]` and it works.  But I don't know if it's OS agnostic.

**Comment by kaste** [comment]
Hi @jackysee! `split('\n')` is correct here since we switched to universal newlines (t.i. we normalize line endings as soon as possible) in SublimeLinter since then.

Can you just push the change you made locally into a PR?

**Comment by jackysee** [comment]
https://github.com/SublimeLinter/SublimeLinter-eslint/pull/263
