### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by Onumis** [SublimeLinter/SublimeLinter-eslint#265]
Getting error on ST3 startup: 

```
SublimeLinter: #1 eslint ShipmentTracker.js ERROR:
==================================================

/usr/bin/env: ‘node’: No such file or directory
```

but I do have node, installed through NVM:

```
$ which node
/home/nuno/.nvm/versions/node/v10.14.1/bin/node
$ which eslint
/home/nuno/.nvm/versions/node/v10.14.1/bin/eslint
```

How can I fix this?

**Comment by kaste** [comment]
Several things you can do. Note that this is a genaral Sublime thing esp. on Mac with nvm and googling for this exact error should give you many results.

1. Start Sublime from the Terminal e.g. `subl .` 
2. Try manual configs, like

  https://github.com/SublimeLinter/SublimeLinter/issues/1118#issuecomment-436656984
  https://github.com/SublimeLinter/SublimeLinter/issues/1118#issuecomment-417152831

3. Follow the instructions in https://github.com/SublimeLinter/SublimeLinter/pull/1509

**Comment by ziaulrehman40tkxel** [comment]
Opening sublime from console fixes the issue, weird. Though i would like it to work regardless of how sublime was opened

**Comment by darthleslin** [comment]
// SublimeLinter Settings - User
{
    "debug": true,
    "gutter_theme": "Circle",
    "linters": {
        "phpcs": {
            "disable": false,
            "executable": "$HOME/.config/composer/vendor/bin/phpcs"
        },
        "eslint": {
            "disable": false,
            "args": [],
            "excludes": [],
            "env": {
                "PATH": "$HOME/.nvm/versions/node/v12.18.1/bin"
            }
        }
    }
}

**Comment by darthleslin** [comment]
// SublimeLinter Settings - User
{
    "debug": true,
    "gutter_theme": "Circle",
    "linters": {
        "phpcs": {
            "disable": false,
            "executable": "$HOME/.config/composer/vendor/bin/phpcs"
        },
        "eslint": {
            "disable": false,
            "args": [],
            "excludes": [],
            "env": {
                "PATH": "$HOME/.nvm/versions/node/v12.18.1/bin"
            }
        }
    }
}

**Comment by darthleslin** [comment]
// SublimeLinter Settings - User
{
    "debug": true,
    "gutter_theme": "Circle",
    "linters": {
        "phpcs": {
            "disable": false,
            "executable": "$HOME/.config/composer/vendor/bin/phpcs"
        },
        "eslint": {
            "disable": false,
            "args": [],
            "excludes": [],
            "env": {
                "PATH": "$HOME/.nvm/versions/node/v12.18.1/bin"
            }
        }
    }
}

**Comment by andreyluiz** [comment]
https://github.com/SublimeLinter/SublimeLinter-eslint/issues/205#issuecomment-386191497 works pretty well. :)
