### ISSUE TITLE
slow performance

### ISSUE THREAD

**Issue by michaelknoch** [SublimeLinter/SublimeLinter-eslint#267]
I'm having a very slow experience when using SublimeLinter-eslint on osx. When I start to lint a file it takes about 3 seconds to show the errors. Even when I resolve the linting errors it takes some time for the linting message to disappear. 

VSCode or even atom are way faster when it comes to js linting.
Are there any performance improvements I can try to speedup my linting experience?

**Comment by kaste** [comment]
Hi! This plugin or `eslint` is not per se that slow. Can you open the Sublime console and see if SublimeLinter already logs warnings here. Otherwise enable debug mode for SublimeLinter which will log out how long a lint process took.

**Comment by kaste** [comment]
That's SublimeLinter's panel. I mean the built-in console: from the menu, `View -> Show console`.

**Comment by michaelknoch** [comment]
sorry, my bad


```
SublimeLinter: sublime_linter.py:252  Delay linting '<untitled 189>' for 0.0s
SublimeLinter: sublime_linter.py:252  Delay linting 'calculate.js' for 0.0s
SublimeLinter: linter.py:891          eslint: checking lint mode 'background' vs lint reason 'on_load'
SublimeLinter: #6 linter.py:908       eslint: linting 'calculate.js'
SublimeLinter: #6 linter.py:1305      Running ...

  /Users/michaelknoch/dev/repos/whereismymoney  (working dir)
  $ cat app/calculate.js | /Users/michaelknoch/dev/repos/whereismymoney/node_modules/.bin/eslint --format json --stdin --stdin-filename /Users/michaelknoch/dev/repos/whereismymoney/app/calculate.js

SublimeLinter: #6 linter.py:987       eslint: output:
  [{"filePath":"/Users/michaelknoch/dev/repos/whereismymoney/app/calculate.js","messages":[{"ruleId":"no-restricted-syntax","severity":2,"message":"Using 'ForOfStatement' is not allowed.","line":74,"column":5,"nodeType":"ForOfStatement","source":" ..."}]
SublimeLinter: #6 linter.py:73        eslint output:
[{'errorCount': 2,
  'filePath': '/Users/michaelknoch/dev/repos/whereismymoney/app/calculate.js',
  'messages': [{'column': 5,
                'line': 74,
                'message': "Using 'ForOfStatement' is not allowed.",
                'nodeType': 'ForOfStatement',
                'ruleId': 'no-restricted-syntax',
                'severity': 2,
                'source': '    for (const key of Object.keys(categories)) {'},
               {'column': 9,
                'line': 75,
                'message': "Using 'ForOfStatement' is not allowed.",
                'nodeType': 'ForOfStatement',
                'ruleId': 'no-restricted-syntax',
                'severity': 2,
                'source': '        for (const brand of categories[key]) {'}],
  'source': ".....",
  'warningCount': 0}]
SublimeLinter: sublime_linter.py:449  Linting 'calculate.js' took 1.88s

```

**Comment by kaste** [comment]
Okay, as you can see in the laste line it 'took 1.88s' which is a bit slow. This should be also the time it roughly takes when you run eslint from the command line. 

A couple of things: Are these timings always that slow? Is 'calculate.js' a *huge* file? Do you use eslint plugins which slow down the process? Or just other things like a reloader, prettier, a build process which run at the same and fight for resources?

Anyway, VSCode and Atom basically run eslint in a daemon. You can achieve something similar by installing 'eslint_d'. After that you have to tell the plugin to use the daemon. In the SublimeLinter settings:

```
# pseudo yaml bc it's easier to write
linters:
	eslint:
		executable: ['$folder/node_modules/.bin/eslint_d']
		# OR
		executable: 'eslint_d'  # if it's globally available and in PATH
``` 

(or something similar). 

Since it is probably better to apply this only for specific projects. You can also just modify the project settings:

```
settings:
	SublimeLinter.linters.eslint.executable: [...same as before...]
```

**Comment by michaelknoch** [comment]
I have used eslint_d before and it nearly solves the performance issues. Linting was not as fast as it is with vscode, but for me it was ok.  For some reasons suddenly linting with eslint_d and our project ruleset was broken. I think it's a bug with the new airbnb linting ruleset.

I know this problem is not related to SublimeLinter-eslint, but maybe you have an idea whats happening. This error occurs when using eslint_d from /usr/local/bin or when installed as dev dependency to the project. It even happens when running eslint_d from cli

```
JSON Decode error: We expected JSON from 'eslint', but instead got this:
Error: Cannot read config file: /Users/michaelknoch/dev/flow/smartphone-app/node_modules/eslint-config-airbnb-base/rules/strict.js
Error: ENOENT: no such file or directory, open '/Users/.../app/node_modules/eslint-config-airbnb-base/rules/strict.js'
Referenced from: '/Users/.../app/node_modules/eslint-config-airbnb/index.js
Referenced from: '/Users/.../app/.eslintrc.js
```

**Comment by kaste** [comment]
Closing bc it's unlikely that this becomes an actionable issue.
