### ISSUE TITLE
Option to exclude certain extensions

### ISSUE THREAD

**Issue by brettimus** [SublimeLinter/SublimeLinter-eslint#269]
[According to ESLint docs](https://eslint.org/docs/user-guide/configuring#specifying-file-extensions-to-lint), the only way to specify which file extensions to lint is with a command-line option.

Providing an interface to this in the user preferences config would be handy.

**Comment by kaste** [comment]
Hm, from the documentation

> Note this flag only takes effect in conjunction with directories, and will be ignored if used with filenames or glob patterns.

We lint by sending code via stdin. 🤔 

Have you seen http://www.sublimelinter.com/en/stable/linter_settings.html#excludes

**Comment by brettimus** [comment]
I forgot about excludes for _sublime linter_ duh doy. 

Thanks @kaste!
