### ISSUE TITLE
VueJS file linting

### ISSUE THREAD

**Issue by codigodo** [SublimeLinter/SublimeLinter-eslint#272]
I'm not able to figure out what this error is about, on all vuejs files.

Currently using SublimeLinter + SublimeLinter-eslint

![Screen Shot 2019-03-26 at 2 02 15 PM](https://user-images.githubusercontent.com/19627351/55021881-e298cc80-4fcf-11e9-9546-e80cedfd121b.png)

```
// .eslintrc.js
module.exports = {
  root: true,
  parserOptions: {
    sourceType: 'module',
    parser: 'babel-eslint'
  },
  env: {
    browser: true
  },
  extends: ['prettier', 'prettier/standard', 'plugin:vue/recommended'],
  plugins: ['vue', 'prettier'],
  rules: {
    'prettier/prettier': 'error'
  }
};
```

```
// .prettierrc
{
  "singleQuote": true
}
```

**Comment by kaste** [comment]
I never used prettier within eslint (I use them side by side) but here it just looks like you use prettier to generate lint errors (not just for fixing). You explicitly tell it to do so `'prettier/prettier': 'error'`

**Comment by codigodo** [comment]
> I never used prettier within eslint (I use them side by side) but here it just looks like you use prettier to generate lint errors (not just for fixing). You explicitly tell it to do so `'prettier/prettier': 'error'`

The prettier auto format is supposed to fix the errors, no?

**Comment by kaste** [comment]
I don't think this will fix errors. eslint only fixes if you tell it to do so, e.g. `--fix` on the cli otherwise it reports those errors, no?
