### ISSUE TITLE
Linting highlights are slow to show/hide

### ISSUE THREAD

**Issue by carc1n0gen** [SublimeLinter/SublimeLinter-eslint#273]
I know something like this has been brought up before, but since it is closed I thought I would bring it up again.  If any more debug information is needed I will add.

**Sublime**:

![sublime](https://user-images.githubusercontent.com/8248986/55241649-e582ff80-5211-11e9-8c9f-570453a1a1b1.gif)

**VSCode**
![vscode](https://user-images.githubusercontent.com/8248986/55241660-ec117700-5211-11e9-8925-346a74f8547b.gif)

**Comment by kaste** [comment]
You should see in debug mode how long the actual linting takes. It will also print the debounce/wait delay. The highlighting itself is usually not the problem.

**Comment by carc1n0gen** [comment]
I can't show the full output as it contains the json tokenized source code from my company, but I can show how long it took:

```
SublimeLinter: sublime_linter.py:507  Linting 'YesNoModal.js' took 1.36s
```

**Comment by carc1n0gen** [comment]
I've seen it range from 1.2s to 1.6s

**Comment by kaste** [comment]
Then add the debounce time to that, and you can have a 2s delay in total. 

Usually: try to setup eslintd, or find out why eslint is rather slow (plugins, complex config).

**Comment by carc1n0gen** [comment]
Both my vscode and sublime are using the same eslint/config for this project and vscode lints instantly. So I am quicker to put the blame on Sublime/SublimeLinter/SublimeLinter-eslint than plugins/config.  Let me create a minimal vanilla eslint project and report back

**Comment by kaste** [comment]
Yeah okay, but then you must compare Code timings linting python code. Code runs on node and uses this execution env for its JS/TS experience.

**Comment by carc1n0gen** [comment]
I do python on vscode all the time and linting there with flake8 is also instant


vscode: 

![vscode2](https://user-images.githubusercontent.com/8248986/55250659-1456a100-5225-11e9-96ed-9ba8eb648ba9.gif)

It's worth noting that the SublimeLinter-flake8 is also instant.  I'm only having an eslint issue in Sublime

I still have to see if I see the same sublime issue with a minimal project.  Will follow up tonight

**Comment by carc1n0gen** [comment]
Okay, I created a single file project, with a single semicolon rule, and the result is much better, which is actually unfortunate to me because it means there's pretty much nothing to debug, or help improve.  Still don't understand why vscode can lint the same project with same configuration so fast.  I will close this now though, and maybe look in to eslintd as I had never heard of it.
