### ISSUE TITLE
Add command to inject 'eslint-disable-line [reason]' comments

### ISSUE THREAD

**Issue by switz** [SublimeLinter/SublimeLinter-eslint#278]
Sometimes I want to disable a line from linting for the error given, it would be nice to have a command to do this automatically:

```
'foo\.js'
```

errors: `no-useless-escape`

Running the command would do:

```
'foo\.js', // eslint-disable-line no-useless-escape
```

Maybe this is outside of the scope of this library (since it's more passive than active), but it would be a useful thing for me.

**Comment by kaste** [comment]
Yesss! This would be really nice.

**Comment by kaste** [comment]
This has been implemented in the latest SublimeLinter version 🚀

**Comment by tukusejssirs** [comment]
> This has been implemented in the latest SublimeLinter version rocket

@kaste, may I know which version is that? In [GitHub Releases](https://github.com/SublimeLinter/SublimeLinter-eslint/releases), it says that `v4.2.1` is the latest version, however, using Package Control I have installed `v4.16.2`. I presume you use semver, therefore it look like my installed version is newer (which seems to be wrong).

Anyway, I can’t make neither of the following lines work to override the `.eslintrc` config on indentation:

```js
/* eslint indent: ['error', 'tab'] */
/* eslint-disable indent */
```

Thanks for SublimeLinter and your help! :smiley:
