### ISSUE TITLE
no-undef error in ES6 template literal

### ISSUE THREAD

**Issue by dotherightthing** [SublimeLinter/SublimeLinter-eslint#280]
## Source file

```
// ./file.js
const b = "test";
const a = `eslint ${b}`;
```

## ESLint configuration

```
// ./.eslintrc
{
  "parserOptions": {
    "ecmaVersion": 6
  },
  "env": {
    "es6": true
  },
  "rules": {
    "no-undef": 2
  }
}
```

## Software versions

* MacOS: Sierra 10.12.6
* Sublime Text: 3.2.1
* ESLint: v6.1.0 (`sudo npm install -g eslint`, `eslint -v`)
* SublimeLinter-eslint: v4.1.6

## Expected result

Run via commandline: `eslint file.js` = no errors

## Actual result

Save file in Sublime Text 3 = `error  eslint:no-undef  'b' is not defined.`

**Comment by kaste** [comment]
Well, maybe that's an issue with eslint 6. First, enable `debug` in the settings for SublimeLinter. Then it will print the actually `cmd` and working dir SublimeLinter uses here in Sublime's console. Likely the cmd is okay but the working dir might differ from the command line.

**Comment by dotherightthing** [comment]
@kaste Sorry, it looks like this was actually a quirk with files named `gulpfile.js`.

I can resolve this by changing the file type in the bottom right hand corner to 'JavaScript', then resaving the file. This needs to be done every time I open that file.

**Comment by kaste** [comment]
Wonder which plugin you use here. Maybe from the menu `View > Syntax > Open all ...` can help you here.

**Comment by dotherightthing** [comment]
@kaste Thanks, that option is already checked but is ignored.
