### ISSUE TITLE
What do I put where to get sublime to load eslint?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [SublimeLinter/SublimeLinter-eslint#291]
Eslint is installed globally, configured, and works in the terminal. SublimeLinter and Sublime-contrib-eslint are both installed and enabled. What magical entries go in `sublimeLinter.sublime-settings`? I'm getting nowhere with the documentation, or digging though old similar issues.

The main goal is to make it work with js files, and preferably respect project `.eslintrc` files.

**Comment by kaste** [comment]
You shouldn't need to set anything. But note this is the SublimeLinter-eslint repo here (without the contrib).

Best is to enable debug mode in the settings, then look at the console for what's actually happening.

**Comment by narcolepticinsomniac** [comment]
[log](https://pastebin.com/HjQnzppj)

Appreciate the help. As far as the contrib, multiple tutorials I looked up said to install both. What else did I do wrong that I'm getting "No installed linter matches the view"?

**Comment by kaste** [comment]
From that log it looks like you have eslint_d installed which seems outdated (look at all those warnings eslint_d print when reloading).

Just uninstall that one and instead use this official repo. Then we see what happens next.

**Comment by narcolepticinsomniac** [comment]
Nah, to be extra sure, I re-installed a fresh Sublime portable and only installed SublimeLinter. I get the same "No installed linter matches the view". [log](https://pastebin.com/e0g8sAPd)

Hopefully irrelevant, but when I was digging around for solutions the other day, I came across [this ancient issue](https://github.com/SublimeLinter/SublimeLinter-eslint/issues/18) regarding Win 8, which is what I'm using.

**Comment by kaste** [comment]
In this log this plugin here is not installed.

**Comment by narcolepticinsomniac** [comment]
SublimeLinter is installed, and eslint is installed. What plugin exactly are you referring to?

**Comment by kaste** [comment]
The one you're posting in. SublimeLinter is the core/host. You need adapters/plugins like this one for the actual linters.

**Comment by narcolepticinsomniac** [comment]
Right... duh. Musta skipped a pretty important step when I re-installed, but I had it previously. Ended up setting it up a lot better following a tutorial for doing it through the vscode terminal. The initial step of setting up the config files so you can actually run `eslint --init` successfully provides a much more useful template than suggesting the creation of an empty config after the fact.

**Comment by kaste** [comment]
💐

**Comment by narcolepticinsomniac** [comment]
Forgot to say thanks. Appreciate you taking the time. =)
