### ISSUE TITLE
ESLint does not allow global configurations anymore

### ISSUE THREAD

**Issue by stevenxxiu** [SublimeLinter/SublimeLinter-eslint#292]
ESLint does not allow global configurations anymore, see [Personal Configuration File (deprecated)](https://eslint.org/docs/user-guide/configuring#personal-configuration-file-deprecated).

This means that this package shouldn't be used to lint global files. Can this package be disabled if it's not in a project, instead of printing the following warning every time?

    SublimeLinter: WARNING: eslint cannot locate 'eslint'

**Comment by kaste** [comment]
The setting is called `"disable_if_not_dependency"`, you can find it when you open the SublimeLinter settings.
