### ISSUE TITLE
ReadMe: You can restore the old behavior by setting selector to its old value...where? exactly?

### ISSUE THREAD

**Issue by ablomberg** [SublimeLinter/SublimeLinter-eslint#294]
> Starting with v4.2 of this plugin, eslint will only lint '*.js' files for standard, vanilla configurations without further plugins. You can restore the old behavior by setting selector to its old value:

```
"linters": {
    "eslint": {
        "selector": "source.js - meta.attribute-with-value"
    }
}
```

Which plugin and file, please? Mac OSx, SublimeText3.

I have gotten everything else working except html linting with eslint. Tried putting it in my .eslintrc, but got an error. Does it go in my sublimelint-eslint settings? eslint settings? sublime settings? .eslintrc in a specific way?

An accessibility WCAG plugin I need depends on ESLint, or I'd just use htmlHint. Sorry for the beginner's question. Thanks!

**Comment by kaste** [comment]
You put it either in the SublimeLinter settings or your project settings. http://www.sublimelinter.com/en/latest/settings.html 

You access the (global) SublimeLinter settings via Command Palette (ctrl+p)  `SublimeLinter Settings`, the project settings via `Edit Project`.

**Comment by kaste** [comment]
Probably solved

**Comment by pierresh** [comment]
I also met that problem and I fixed as follow in **SublimeLinter.subline.settings** (I develop with Angular and Vue):

```json
"linters": {
    "eslint": {
        "selector": "source.js, source.ts, text.html, text.html.vue, source.json - meta.attribute-with-value"
    }
}
```
