### ISSUE TITLE
Prettier: "text.trimEnd is not function" with eslint / eslint-plugin-prettier

### ISSUE THREAD

**Issue by YuriGor** [SublimeLinter/SublimeLinter-eslint#295]
Hi guys I just created a new project and installed most recent
```
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.3",
    "prettier": "^2.0.5"
```
And when trying to lnt I see 
"TypeError: text.trimEnd is not a function"
which comes from prettier.
I see prettier starting from v2 requires nodejs v10+
But I had node 11 and tried to upgrade to node v14
In sublime linter settings I have 
```
{
	"paths": {
        "linux": [
        	"/home/gor/.nvm/versions/node/v14.0.0/bin"
```
And used to have v11 before trying to upgrade.
When I run `npx eslint` in terminal it works fine
`npx prettier` separately also works without errors.

I added console.log to prettier and I see in sublime console 
` v8.10.0`

Any idea how it's possible to still run this old node version in sublime somehow?

**Comment by kaste** [comment]
Same error if you start Sublime from your Terminal with everything setup as expected?

**Comment by YuriGor** [comment]
No, if started from terminal - it works fine...
I just found in .bash_profile assigning this old version of node to PATH, removed it but it didn't help..
maybe will try to reboot..

**Comment by kaste** [comment]
I also don't think setting the path to `node/v14.../bin` can help here because we're actually looking and executing the eslint binary from your "node_modules" which in turn execs "../eslint/bin/eslint.js" which in turn has the bang "#!/usr/bin/env node".

**Comment by kaste** [comment]
> No, if started from terminal - it works fine...

Ok, can't give any tips here but there are enough people in the official Sublime forum (regardless if you paid or not) knowing exactly how to get the proper ENV into Sublime when using whatever WindowManager.

**Comment by YuriGor** [comment]
Ok thanks a lot for the idea to run sublime from termonal

**Comment by YuriGor** [comment]
If someone also, I fixed this by adding:
```json
{
  "linters": {
    "eslint": {
        "env": {"PATH":"/home/gor/.nvm/versions/node/v14.0.0/bin"}
    }
  }
}
```
to sublime linter's settings as suggested in [SublimeLinter's troubleshooting docs](http://www.sublimelinter.com/en/stable/troubleshooting.html)
