### ISSUE TITLE
Auto fix the file?

### ISSUE THREAD

**Issue by coodoo** [SublimeLinter/SublimeLinter-eslint#303]
Is it possible to auto fix the file being lint? Just like running `eslint --fix` with the `--fix` argument?

**Comment by kaste** [comment]
This is not implemented right now.  PR welcome. The xo plugin which is a wrapper around eslint actually ships this. Shouldn't be too complicated to adapt their code.

**Comment by chrisgrieser** [comment]
@coodoo You can use the eslint formatter plugin to autofix on save: https://gist.github.com/piratefsh/7607b6c166259a50b486c428712e3e69
