### ISSUE TITLE
[Error] JSON Decode error: We expected JSON from 'eslint', but instead got this:

### ISSUE THREAD

**Issue by DimitrisRK** [SublimeLinter/SublimeLinter-eslint#305]
Recently, I started receiving the following error and my linter stopped working at the same time.
I have been using eslint_d as executable for months now and had no issues.

```
JSON Decode error: We expected JSON from 'eslint', but instead got this:
Error: Cannot find module 'write'
Require stack:
- /home/dev/repo3/node_modules/flat-cache/utils.js
- /home/dev/repo3/node_modules/flat-cache/cache.js
- /home/dev/repo3/node_modules/file-entry-cache/cache.js
- /home/dev/repo3/node_modules/eslint/lib/cli-engine/lint-result-cache.js
- /home/dev/repo3/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/dev/repo3/node_modules/eslint/lib/cli-engine/index.js
- /home/dev/repo3/node_modules/eslint/lib/api.js
- /usr/local/lib/node_modules/eslint_d/lib/linter.js
- /usr/local/lib/node_modules/eslint_d/node_modules/core_d/lib/server.js
- /usr/local/lib/node_modules/eslint_d/node_modules/core_d/lib/daemon.js


Be aware that we only parse the last line of above output.
```

It's also really strange that package uses modules from my current working directory while I have installed everything globally.
This error causes linter not to operate at all and one can be prone to bad code syntax.

**Comment by kaste** [comment]
I'm not familiar with this output; actually we print this so users can probably help themselves.  Usually if it worked before you upgraded some part of your system.  Maybe the global eslint_d is not compatible with the local eslint.

**Comment by DimitrisRK** [comment]
> I'm not familiar with this output; actually we print this so users can probably help themselves. Usually if it worked before you upgraded some part of your system. Maybe the global eslint_d is not compatible with the local eslint.

Hello. Thanks a lot for replying. Problem was solved when I started using pure eslint executable instead of eslint_d.
I recall doing this change because eslint was making my editor slower, but it seems to be good now.

For anyone digging this issue for information, I recently upgraded to node 15 and that's when issues with eslint_d occured.

**Comment by kaste** [comment]
Per README eslint_d is even node versions only.
