### ISSUE TITLE
Sublime​Linter-eslint is not available anymore from Package Control

### ISSUE THREAD

**Issue by DenizOkcu** [SublimeLinter/SublimeLinter-eslint#306]
If you want to install Sublime​Linter-eslint from Package Control it does not show up in the list of installable packages.
<img width="464" alt="Bildschirmfoto 2021-03-26 um 10 15 16" src="https://user-images.githubusercontent.com/1931144/112609905-66365f80-8e1c-11eb-8b96-38903d77351a.png">
<img width="298" alt="Bildschirmfoto 2021-03-26 um 10 17 25" src="https://user-images.githubusercontent.com/1931144/112610288-ce854100-8e1c-11eb-99e7-af95b23069f2.png">

On the Package Control site it says: "NEEDS REVIEW"
https://packagecontrol.io/packages/SublimeLinter-eslint

What can we do to get it back?

**Comment by akrikos** [comment]
https://packagecontrol.io/news#2021-02-24-Package_Takeover_Vulnerability_Notification explains what's going on. Looks like it needs "to be manually reviewed", I assume by someone in the Package Control team? I created an issue on the packagecontrol.io repo in case that provides more visibility.

**Comment by DenizOkcu** [comment]
Thank you this is great! Looking forward getting it reviewed.

**Comment by Shelagh-Lewins** [comment]
I have the same problem - Sublime Text 3 is only showing eslint_d and I can't get that to work. Is there any workaround to manually add a package?

**Comment by metadaddy** [comment]
It seems to be back in Package Control now - I just installed `Sublime​Linter-eslint` with no problems.
