### ISSUE TITLE
SublimeLinter showing inexplicable errors in a typescript file

### ISSUE THREAD

**Issue by akatechis** [SublimeLinter/SublimeLinter-eslint#312]
I have a typescript file wherein I'm using `allowSyntheticDefaultImports` style imports (importing the default export, where the default export is synthetically composed as an object of all named exports).

When I run my `eslint` command in a terminal, I get no errors:

```
$ yarn lint
yarn run v1.22.5
$ eslint .
Done in 1.19s.
```

Same when I run my test command (mocha) which executes the file in question:

```
$ yarn test
yarn run v1.22.5
$ nyc mocha


  koa-hotwire middleware
    turbo-frame rendering
      √ renders pages when using ctx.view in a handler
      √ passes ctx.state to render calls
      √ wraps turboframes in custom elements when requested
      √ optimizes rendering when a specific turbo-frame is requested
      √ returns an error when the requested frame is not in the view
      √ does nothing when the handler doesn't produce a view


  6 passing (49ms)

----------------|---------|----------|---------|---------|-------------------
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------------|---------|----------|---------|---------|-------------------
All files       |     100 |      100 |     100 |     100 |
 koa-hotwire.ts |     100 |      100 |     100 |     100 |
----------------|---------|----------|---------|---------|-------------------
Done in 2.67s.
```

However, in Sublime, I see the following errors, where it seems like the linter is reporting 0 errors/warnings:

![image](https://user-images.githubusercontent.com/1058931/120927604-6d48dc00-c6af-11eb-8529-47569fc33548.png)

System:
* Windows 10
* Sublime stable channel, build 4107
* Package versions:
```
    "eslint": "^7.28.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
```
* My eslint configuration:
```
module.exports = {
  env: {
    node: true,
    es2021: true,
  },
  extends: ['standard'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 12,
    sourceType: 'module',
  },
  plugins: [
    '@typescript-eslint',
  ],
  rules: {
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'always-multiline',
    }],
  },
  ignorePatterns: [
    'artifacts/',
  ],
}
```

**Comment by kaste** [comment]
Hm, you probably have some other plugin especially for TS running.  SublimeLinter reports this file as "ok" in the status bar, so the underlined word come from something else.  I also think the popup does not have our current style, although it is similar.

**Comment by akatechis** [comment]
Oh, well that's embarassing. You're completely right! I removed/re-installed the `typescript` package, and that fixed it. Closing this now.

Thanks, @kaste!
