### ISSUE TITLE
Question: How does this plugin set CWD?

### ISSUE THREAD

**Issue by IPWright83** [SublimeLinter/SublimeLinter-eslint#317]
Hey, I hope you don't mind the question here. I've been trying to fix issues I've been having with a different package (https://github.com/TheSavior/ESLint-Formatter/issues/89) as I don't believe there's a way you autofix on save with the linter?

I've got a PR on the go for `eslint_d` (https://github.com/mantoni/eslint_d.js/issues/202) to fix my problem, which all stems from the current working directory being incorrect when snapping a tab into a new window from Sublime. But then I noticed that this plugin doesn't have the same issue I don't believe (in that whether I've got a single file open, or a project open with a file within it) it seems to be using the correct linter settings and not hitting the slow down issues.

Can I ask is there something specific going on in SublimeLinter or SublimeLinter-eslint to set the current working directory that might it behave better than other packages?

**Comment by kaste** [comment]
Typically, the `cwd` is where `package.json` is.  The default is here https://github.com/SublimeLinter/SublimeLinter/blob/8ebb2f035f3ef81ebb185e187c466103b3fc946a/lint/linter.py#L1039  

ESLint_Formatter takes the first open folder https://github.com/TheSavior/ESLint-Formatter/blob/b76c47ee3d59f7586cc3c8bae8c5bbff64e38407/ESLint-Formatter.py#L176-L185 which is simpler but fails if you drag a view into a new window.

**Comment by IPWright83** [comment]
Thanks @kaste, that's really helpful! Also seeing that you can set the CWD for a sub process. I don't know Python very well but am going to try and replicate this in that other plugin.

Can I just confirm that auto fixing is still out of scope for sublime linter? Makes sense if it is, but want to make sure my effort is well spent :)

**Comment by kaste** [comment]
It is not out of scope per se; it lacks a good implementation.  The auto-formatters always have (or had -- has that been solved?) the problem of blocking Sublime's UI; usually they run on-pre-save.  (The linters run on-modified and/or on-_post_-save.)  They usually replace the complete buffer or somehow modify parts of the buffer which leads to cursor and/or viewport jumps.  I actually don't know which parts of SublimeLinter are actually useful and re-usable for the formatters.  (The configuration?)

**Comment by IPWright83** [comment]
Gotcha, yeah I guess it's probably the configuration that's most useful.

I think ESLint-Formatter does a whole load of stuff to try and manage the current state of the buffer, so yeah it is a different problem. Thanks.

I've submitted a PR to the fixer which I think should work.
