### ISSUE TITLE
eslint cannot locat 'eslint'

### ISSUE THREAD

**Issue by AK-CHP1** [SublimeLinter/SublimeLinter-eslint#324]
I am using Sublime Text Build 4126. I have installed `eslint` globally using npm. Then I installed `SublimeLinter` and `SublimeLinter-eslint` using package control. But when I am opening a javascript file, I am getting the following error:
~~~
SublimeLinter: WARNING: eslint cannot locate 'eslint'
Please refer to the readme of this plugin and our troubleshooting guide: http://www.sublimelinter.com/en/stable/troubleshooting.html
WARNING:SublimeLinter.plugin.eslint:eslint cannot locate 'eslint'
Please refer to the readme of this plugin and our troubleshooting guide: http://www.sublimelinter.com/en/stable/troubleshooting.html
~~~
I am comfortably able to access `eslint` from the command line. Here is my `PATH` configuration:

~~~
/home/aayush/.pyenv/shims:/home/aayush/.local/bin:/home/aayush/.miniconda3/condabin:/home/aayush/.nvm/versions/node/v19.0.0/bin:/home/aayush/.pyenv/bin:/home/aayush/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/aayush/.local/bin   
~~~
I use `nvm` for version management. I am also getting similar issues with other extensions like `SublimeLinter-jshint` and `jsPrettier`. Though I am getting no such issues with similar python extensions like `SublimeLinter-flake8` or `AutoPEP8` Please help me to fix this issue.

Thanks

**Comment by kaste** [comment]
It's `nvm`.  Implementing https://github.com/SublimeLinter/SublimeLinter/issues/1795 would solve this probably.  (iirc `volta` would work here out of the box.)

Usually `nvm` changes your PATH in the Terminal, and Sublime Text might see a different one than what you think and posted.  You can for example start Sublime via `subl .` from the Terminal and it should inherit the shells ENV (and PATH).  You can also configure the `executable` setting for each node or nvm installed linter.  (Personally, I would recommend not to use nvm anymore but use a successor but that may be no options for you.)

**Comment by AK-CHP1** [comment]
I got it. `nvm` only adds it's directory to `PATH` when you open terminal, 
as you suggested and also follows from !(this discussion)[https://forum.sublimetext.com/t/eslint-support-for-sublime-text/65850/8], the main problem is `nvm`.

So, as you told I decided to ditch `nvm` and now I am using `volta` Everyting is working fine. You may close this issue.

Thanks

**Comment by kaste** [comment]
👍
