### ISSUE TITLE
Support eslint flat config

### ISSUE THREAD

**Issue by silverwind** [SublimeLinter/SublimeLinter-eslint#335]
Since eslint 9, the new flat config format is the new default, and I think it likely needs explicit support in this plugin. See this link for details:

https://eslint.org/docs/latest/use/configure/migration-guide

**Comment by kaste** [comment]
Don't we support this already?

**Comment by silverwind** [comment]
I have not tried it yet, but I guess I could. I have not yet upgraded my configs to v9 or flat format yet.

**Comment by silverwind** [comment]
I set up a [minimal test repo](https://github.com/silverwind/eslint-flat-test) with flat config, and it worked, thanks.

<img width="119" alt="image" src="https://github.com/SublimeLinter/SublimeLinter-eslint/assets/115237/5683aaae-bd7e-49e8-b546-cee8bf39dfae">
