### ISSUE TITLE
.html <script/> extraction broken when .eslintrc includes html plugin

### ISSUE THREAD

**Issue by TremayneChrist** [SublimeLinter/SublimeLinter-eslint#87]
I have the html plugin (https://github.com/BenoitZugmeyer/eslint-plugin-html) specified in .eslintrc for command line usage...

"plugins": [
  "html"
]

I went to add the SublimeLinter-eslint plugin to Sublime, however, linting html files does not work as the eslint-plugin-html conflicts with the selectors map in linter.py...

'html': 'source.js.embedded.html'

Removing the plugins option in .eslintrc fixes the issue in Sublime but breaks command line usage

**Comment by TremayneChrist** [comment]
I tried a fresh install of sublime also removing Sublime folder in C:\Users\USER\AppData\Roaming and now weirdly it needs the eslint-plugin-html to work and all other issues are fixed, like #88

**Comment by roadhump** [comment]
Does eslint work in html files if `eslint-plugin-html`is disabled?

**Comment by Standard8** [comment]
> Does eslint work in html files if `eslint-plugin-html` is disabled?

If eslint is run on its own without the plugin, then no, it doesn't support html files, it complains about the script tags and just gives up.

With the html plugin, eslint functions fine.

**Comment by roadhump** [comment]
Sorry, I mean does SublimeLinter-eslint work without `eslint-plugin-html`? Because it should, SublimeLinter extracts code from `script` tags and passes it to plugin. It is the same work `eslint-plugin-html` does with `eslint`. I wonder if it does not work for this bug.

**Comment by Standard8** [comment]
Yes, SublimeLinter-eslint works without the html plugin - although it fails on no-trailing-spaces/eol-last (as referenced in issue #88).

**Comment by kaste** [comment]
It would be very helpful if you'd remove the `html`selector from linter.py. (Or is this pluggable?) Since there is the `eslint-plugin-html` I think people should just use that. I mean having both just doesn't work. And a working eslint on the command line is a must, so I don't see the option to remove the plugin from my `eslintrc` here.

**Comment by roadhump** [comment]
I don't want to make `eslint-plugin-html` mandatory for `SublimLinter-eslint` to work with html. Honestly, I think not so many developers use inline scripts in html now. Unfortunately, `SublimeLinter` does not allow to rewrite `selectors` config per project, what can be a solution. Probably it is a case when you can fork/clone repo to ST plugins and change it for your needs.

**Comment by mgibas** [comment]
I second @kaste - this is up to eslint (and its plugins system), not Sublimelinter which is just a proxy.
> Honestly, I think not so many developers use inline scripts in html now

We are writing web components and its pretty natural that you have html + js in single *.html file.

**Comment by Standard8** [comment]
@roadhump If I read you correctly, you're suggesting a fork for the "no-html" option.

Would a slightly different option be to publish SublimeLinter-eslint without the html option, and have a separate plug-in than then depends on this one (and use inheritance) to add the html parsing?

**Comment by kaste** [comment]
Closing since this is implemented in SL4
