### ISSUE TITLE
eol-last rule does not work in <script/> tags

### ISSUE THREAD

**Issue by TremayneChrist** [SublimeLinter/SublimeLinter-eslint#88]
ESLint rule - Require file to end with single newline (eol-last) should be excluded when linting script tags in html.

Or, plugin should support using eslint-plugin-html #87

**Comment by roadhump** [comment]
It looks like this code produces the same `eol-last` error in both cases, in SublimeText with this plugin and in console with `html` ESLint plugin

```
<script>var a = 'xx';</script>
```

and this code is correct is both cases

```
<script>
var a = 'xx';
</script>
```

It seems like `html` plugin does the same work as `selectors = { 'html': 'source.js.embedded.html'}` option of SublimeLinter. I don't think it is worth to replace this option somehow.

**Comment by Standard8** [comment]
The no-trailing-spaces option also fails at the end of script tags, e.g.

```
<body>
  <script>
    var a = 'xx';
  </script> <!-- <<<< fails here -->
</body>
```

I don't understand the comment about selectors to use.

**Comment by roadhump** [comment]
It seems that in your case SublimeLinter extracts and gives eslint as input this text
```

______var aa = 'xx';
____    
```

where I replace whitespaces with underscores. So the last line is not empty eol and eslint alerts. I really don't know what is correct way to fix it: SublimeLinter extracts correct, it can't make assumptions that text should be "unindented", so as eslint itself. Probably disable `eol-last` rule in JS blocks inside HTML files is the easiest way.

It seems like `eslint-plugin-html`works correct in this case, but it seems unpractical to make it a requirement for this plugin to work with HTML files.

**Comment by Standard8** [comment]
Whilst SublimeLinter extraction is "correct", I'd argue that it should actually strip those last whitespaces as they are on the </script> line. Its standard functionality to inset the html tags. So I think this implies this is more an issue with SublimeLinter than this plugin.

**Comment by broonage** [comment]
I had a bit of a hard time with this. But I was able to get eslint and the react and html plugins working. To say the least it isn't very obvious.

**Comment by kaste** [comment]
Not a fault of this plugin, must be solved in SublimeLinter core, but I'm not convinced.
