### ISSUE TITLE
<script> in HTML file results in "Parsing error: Unexpected token <"

### ISSUE THREAD

**Issue by OliverJAsh** [SublimeLinter/SublimeLinter-eslint#99]
``` json
// package.json
{
  "name": "eslint-html",
  "private": true,
  "dependencies": {
    "eslint": "^1.7.2"
  }
}
```

``` json
// .eslintrc
{}
```

``` html
<!-- foo.html -->
<html>
    <body>
        <script>
            var foo = function () {

            };
        </script>
    </body>
</html>
```

I get the following error: `Parsing error: Unexpected token <` at line 3 at the start of `<script>`.

I understand SublimeLinter patches the HTML syntax so it can lint inline scripts. It reads the other HTML fine, but stumbles on `<script>`. Why is this not working?

I am using the standard HTML syntax. This may be a duplicate of https://github.com/roadhump/SublimeLinter-eslint/issues/81

**Comment by roadhump** [comment]
It seems like patch of SublimeLinter does not work for you. I suppose it is a bug of SublimeLinter itself, probably you should check it with another JS linter (JSCS, for example), will it work with himl files and `script` tags, and post bug to SublimeLinter if it also does not work properly.

**Comment by OliverJAsh** [comment]
Just tested and yes, the same issue happens with jscs. I will follow up with SublimeLinter

**Comment by OliverJAsh** [comment]
Posted at https://github.com/SublimeLinter/SublimeLinter3/issues/356

**Comment by groteworld** [comment]
As of sublimehq/Packages@0417e42 these changes have been made to the default HTML syntax. You will need newest build ST3103.

CSS may be having issue, I'm confirming in Packages issue sublimehq/Packages#106 but `<script>` has been properly fixed.

**Comment by LeEnno** [comment]
Issue still persists for me with build ST3103.

**Comment by groteworld** [comment]
Build 3109 (released in dev today) has these fixes built-in, following the install instructions of [sublimehq/Packages](https://github.com/sublimehq/Packages) you will be able to get the fixes in 3103+. Sorry should have prefaced that better.

**Comment by braver** [comment]
Should be fixed by now then... if not let me know.
